### ISSUE TITLE
Плагин не устанавливается

### ISSUE THREAD

**Issue by Slavenin** [centosadmin/redmine_telegram_common#11]
Здравствуйте!
Redmine 3.3 установлен на сервер из bitnami. 
В папку plugins клонировал этот репозиторий. Внутри папки `redmine_telegram_common`  запустил `/opt/redmine-3.3.3-0/ruby/bin/bundle install`. Всё прошло без ошибок. Далее делаю `/opt/redmine-3.3.3-0/ruby/bin/bundle exec rake redmine:plugins:migrate RAILS_ENV=production` в итоге ошибка 
> /opt/redmine-3.3.3-0/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/rubygems_integration.rb:351:in `block (2 levels) in replace_gem': rake is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
        from /opt/redmine-3.3.3-0/ruby/bin/rake:22:in `<main>'

**Comment by olemskoi** [comment]
Здравствуйте!

Попробуйте запустить "RAILS_ENV=production bundle install" из корня папки "redmine".

**Comment by Slavenin** [comment]
The program 'bundle' is currently not installed. You can install it by typing:
apt install ruby-bundler

**Comment by olemskoi** [comment]
RAILS_ENV=production /opt/redmine-3.3.3-0/ruby/bin/bundle install
из папки "redmine"

**Comment by Slavenin** [comment]
> You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

>If this is a development machine, remove the /opt/redmine-3.3.3-0/apps/redmine/htdocs/Gemfile freeze
by running `bundle install --no-deployment`.

>the list of sources changed
>the dependencies in your gemfile changed


>You have added to the Gemfile:
>* source: https://github.com/arturtr/pidfile.git (at master)
>* telegram-bot-ruby
>* pidfile
>* shoulda
>* minitest-reporters

**Comment by olemskoi** [comment]
RAILS_ENV=production /opt/redmine-3.3.3-0/ruby/bin/bundle install --no-deployment
из папки "redmine"

**Comment by Slavenin** [comment]
...
Installing rack-openid 1.4.2
Installing rbpdf 1.19.2
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /opt/redmine-3.3.3-0/ruby/bin/ruby extconf.rb
creating Makefile

make "DESTDIR=" clean
sh: 1: make: not found

make "DESTDIR="
sh: 1: make: not found

make failed, exit code 127

Gem files will remain installed in /opt/redmine-3.3.3-0/ruby/lib/ruby/gems/2.1.0/gems/redcarpet-3.3.4 for inspection.
Results logged to /opt/redmine-3.3.3-0/ruby/lib/ruby/gems/2.1.0/extensions/x86_64-linux/2.1.0-static/redcarpet-3.3.4/gem_make.out

An error occurred while installing redcarpet (3.3.4), and Bundler cannot continue.
Make sure that `gem install redcarpet -v '3.3.4'` succeeds before bundling.

**Comment by Slavenin** [comment]
Сделал. Результат тот же:

> redmine_telegram_common# /opt/redmine-3.3.3-0/ruby/bin/bundle exec rake redmine:plugins:migrate RAILS_ENV=production
> /opt/redmine-3.3.3-0/ruby/lib/ruby/gems/2.1.0/gems/bundler-1.14.5/lib/bundler/rubygems_integration.rb:351:in `block (2 levels) in replace_gem': rake is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
>         from /opt/redmine-3.3.3-0/ruby/bin/rake:22:in `<main>'
>

**Comment by olemskoi** [comment]
Все же это особенности сборки. Попробуйте найти howto, как добавить плагин в bitnami.
Задача не имеет никакого отношения к плагину.

**Comment by Slavenin** [comment]
До этого поставил плагин redmine_lightbox2 с запуском миграций. Всё установилось без проблем.

**Comment by olemskoi** [comment]
Миграции и установка гемов - это разные вещи.

**Comment by Slavenin** [comment]
запускать нужно как описано тут https://docs.bitnami.com/general/apps/redmine/ только путь до бандлера поменять на абсолютный, если руби нет в системе. 
Спасибо за помощь.
