### ISSUE TITLE
Проблема с авторизацией клиента

### ISSUE THREAD

**Issue by YevhenGit** [centosadmin/redmine_telegram_common#15]
Добрый день, не могу авторизировать Telegram в настройках плагина.
Environment:
  Redmine version                3.3.3.stable
  Ruby version                   2.3.4-p301 (2017-03-30) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2

Redmine Telegram Common plugin version 0.1.1
PhantomJS version 2.1.1
_________________________________________________________________
Log:
D, [2017-07-03T13:06:00.769671 #27551] DEBUG -- : Logout
D, [2017-07-03T13:06:00.769885 #27551] DEBUG -- : {}
D, [2017-07-03T13:06:00.775766 #27551] DEBUG -- : /usr/bin/phantomjs /var/www/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "http://redmine/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Logout"
D, [2017-07-03T13:06:11.381459 #27551] DEBUG -- : http://redmine/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Logout
Push messaging is not supported.
failed: {"type":"AUTH_KEY_EMPTY","code":401,"input":"auth.logOut","stack":"empty stack"}
Error creating/accessing IndexedDB database [object Event]
   http://redmine/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
[0.287] Send req_pq f3d7b07505295d642df2da9b23f618ce
Push messaging is not supported.
Error creating/accessing IndexedDB database [object Event]
   http://redmine/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
[0.088] Send req_pq 8442188def29cf71f20115dc27db5347
[0.144] req_pq error undefined
   http://redmine/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
Get networker error [object Object] undefined

**Comment by constXife** [comment]
Здравствуйте, нам очень жаль, что у вас возникла проблема с использованием плагина. Не могли бы вы попробовать проверить новые изменения из ветки develop (версия 0.1.2-dev)?

Если вы клонировали код плагина из git, то можно выполнить следующие команды

* `cd plugins/redmine_telegram_common`
* `git checkout develop`
* `git pull`
* Перезагрузите ваш редмайн и попробуйте снова авторизоваться в Telegram в настройках плагина

**Comment by YevhenGit** [comment]
Доброго времени суток, обновился до 0.1.2-dev. 
Log: ( часть номера скрыл под *********)
D, [2017-07-04T16:42:27.431391 #10707] DEBUG -- : Login
D, [2017-07-04T16:42:27.431535 #10707] DEBUG -- : {:phone_number=>"380*********"}
D, [2017-07-04T16:42:27.437342 #10707] DEBUG -- : /usr/bin/phantomjs /var/www/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "http://redmine/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%22380*********%22%7D&command=Login"
D, [2017-07-04T16:42:38.059537 #10707] DEBUG -- : http://redmine/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%22380*********%22%7D&command=Login
Push messaging is not supported.
failed: {"type":"AUTH_KEY_EMPTY","code":401,"input":"auth.sendCode","stack":"empty stack"}
Error creating/accessing IndexedDB database [object Event]
   http://redmine/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
[0.285] Send req_pq d8d3ae598a94ae4159d77e0234a47379
Push messaging is not supported.
Error creating/accessing IndexedDB database [object Event]
   http://redmine/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
[0.089] Send req_pq 23313e0c366a2c11205e223bec1a4d49
[0.155] req_pq error undefined
   http://redmine/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
Get networker error [object Object] undefined

P.S.: интернет на сервере через прокси, возможно в этом причина? Предыдущая версия с redmine_intouch (так же предыдущий) работала нормально .... 
P.S.S,: если нужна еще какая нибудь информация отпишитесь.

**Comment by constXife** [comment]
У вас телефон начинается на 3, да? У вас есть возможность проверить телефон, который начинается на 7?

**Comment by YevhenGit** [comment]
Да, на 3, с 7кой возможности проверить к сожалению нету(

**Comment by olemskoi** [comment]
Здравствуйте.

У Вас есть возможность проверить реальный хост с https? Сейчас, насколько я вижу, у Вас "http://redmine/".

**Comment by advokatb** [comment]
Аналогичная проблема. Номер с 380... Протокол http://

**Comment by olemskoi** [comment]
Протокол должен быть https, это требование telegram.

**Comment by constXife** [comment]
Я немного уточню, https нужен для ботов inTouch и ChatTelegram. А авторизация проходит практически локально, нужен только доступ в интернет.

> Инструкций по установке на Редмайн нет? :-(
Достаточно просто установить PhantomJS, чтобы он был виден в системе.

С номером 380 мы разбираемся.

**Comment by Pankraty** [comment]
У меня точно такая же проблема. Номер начинается на 7, соединение по https.

**Comment by constXife** [comment]
Не могли бы вы мне отправить на почту constxife@yandex.ru какой-нибудь из ваших проблемных номеров, чтобы я мог протестировать?

**Comment by Pankraty** [comment]
Отправил

**Comment by KhDmitriy** [comment]
Добрый день. 
Подтверждаю проблему- не могу авторизовать номер.
Environment:
  Redmine version                3.4.1.stable
  Ruby version                   2.3.4-p301 (2017-03-30) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.7.4
  Filesystem                     
Redmine plugins:
  redmine_intouch                1.0.0
  redmine_sidekiq                2.1.0
  redmine_telegram_common        0.1.2
  simple_author_change           0.1.2

phantomjs --version
2.1.1

cat /opt/bitnami/apps/redmine/htdocs/log/telegram_common/telegram-cli.log
D, [2017-07-21T12:34:35.100484 #5484] DEBUG -- : Login
D, [2017-07-21T12:34:35.100645 #5484] DEBUG -- : {:phone_number=>"79678567890"}
D, [2017-07-21T12:34:35.103969 #5484] DEBUG -- : /opt/bitnami/common/bin/phantomjs /opt/bitnami/apps/redmine/htdocs/plugins/redmine_telegram_common/config/phantom-proxy.js "https://it.gig-group.com/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279678567890%22%7D&command=Login"
D, [2017-07-21T12:34:45.915558 #5484] DEBUG -- : https://it.gig-group.com/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279678567890%22%7D&command=Login
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3

**Comment by daos767** [comment]
Номер на 3 так и не авторизируется

**Comment by olemskoi** [comment]
Мы работаем над исправлением этой ошибки.

**Comment by constXife** [comment]
У кого есть проблемы, попробуйте следующие действия.

Попробуйте:

1) Обновить phantomjs до 2.1.1
2) Обновить плагин из develop git ветки
3) Перезагрузить redmine
4) Сбросить кеш по соответствующей кнопке в настройках плагина
5) Попытаться авторизоваться
6) Вероятно вы получите PHONE_CODE_EXPIRED.
7) Подождать минут 10
8) Попытаться снова авторизоваться

**Comment by fetaki** [comment]
Здравствуйте у меня аналогичная проблема
выполнил все вышеуказанные рекомендации

Конфигурация;

Environment:
  Redmine version                3.4.2.stable.16888
  Ruby version                   2.3.3-p222 (2016-11-21) [i686-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.6.17
  Git                            1.7.9.5
  Filesystem                     
Redmine plugins:
  easy_gantt                     1.8
  redmine_agile                  1.4.4
  redmine_favorite_projects      2.0.3
  redmine_people                 1.3.1
  redmine_telegram_common        0.1.3-dev
  redmine_theme_changer          0.3.0

**лог такой вот**
`D, [2017-08-04T11:26:09.182015 #28085] DEBUG -- : Login
D, [2017-08-04T11:26:09.182066 #28085] DEBUG -- : {:phone_number=>"79112814440"}
D, [2017-08-04T11:26:09.183140 #28085] DEBUG -- : /bin/phantomjs --local-storage-path="/opt/redmine-3.4/tmp/telegram_common" /opt/redmine-3.4/plugins/redmine_telegram_common/config/phantom-proxy.js "https://redmine.nansenproject.ru:6060/redmine/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279112814440%22%7D&command=Login"
D, [2017-08-04T11:26:19.302119 #28085] DEBUG -- : https://redmine.nansenproject.ru:6060/redmine/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279112814440%22%7D&command=Login
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3

**Comment by constXife** [comment]
@fetaki, добрый день! Не могли бы вы показать вывод следующий команд в ssh консоли компьютера с redmine?

    $ /bin/phantomjs -v

    $ /bin/phantomjs /opt/redmine-3.4/plugins/redmine_telegram_common/config/phantom-proxy.js  "https://redmine.nansenproject.ru:6060/redmine/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279513683910%22%7D&command=Test"

**Comment by fetaki** [comment]
@constXife, Добрый день!

root@SVR-Redmine:~# phantomjs -v
2.1.1
root@SVR-Redmine:~# phantomjs /opt/redmine-3.4/plugins/redmine_telegram_common/config/phantom-proxy.js  "https://redmine.nansenproject.ru:6060/redmine/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279513683910%22%7D&command=Test"
https://redmine.nansenproject.ru:6060/redmine/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279513683910%22%7D&command=Test
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
ReferenceError: Can't find variable: $
   undefined : 2
    : 3
root@SVR-Redmine:~#

**Comment by constXife** [comment]
И ещё

    $ curl https://redmine.nansenproject.ru:6060/redmine/plugin_assets/redmine_telegram_common/webogram/index.html

**Comment by fetaki** [comment]
root@SVR-Redmine:~# curl https://redmine.nansenproject.ru:6060/redmine/plugin_assets/redmine_telegram_common/webogram/index.html
curl: (60) SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.

**Comment by constXife** [comment]
@fetaki, обновите плагин с ветки develop. Должно помочь. Если не поможет, то попробуйте какими-то другими способами обеспечить доступ для скрипта phantomjs до вышеупомянутого URL.

**Comment by fetaki** [comment]
спасибо, помогло, авторизация прошла

**Comment by daos767** [comment]
Подскажите что вы сделали? Так как я тоже обновился с ветки develop и мне не помогло :(

**Comment by constXife** [comment]
daos767, покажите, пожалуйста, свои логи с log/telegram_common/telegram-cli.log

**Comment by daos767** [comment]
D, [2017-08-09T19:00:21.936629 #1673] DEBUG -- : Login
D, [2017-08-09T19:00:21.936714 #1673] DEBUG -- : {:phone_number=>"380XXXXXXXXXX"}
D, [2017-08-09T19:00:21.938792 #1673] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/opt/redmine/redmine/tmp/telegram_common" --ignor$

вот последнее, номер затер.

**Comment by daos767** [comment]
D, [2017-08-09T19:00:21.936629 #1673] DEBUG -- : Login
D, [2017-08-09T19:00:21.936714 #1673] DEBUG -- : {:phone_number=>"380XXXXXXXXX"}
D, [2017-08-09T19:00:21.938792 #1673] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/opt/redmine/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /opt/redmine/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "http://redmine.ds1.net.ua/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%22380XXXXXXXXX%22%7D&command=Login"

Вот последняя попытка.

**Comment by McAlexVrn** [comment]
Добрый день! Так же обновил с ветки develop, проблема после ввода кода авторизации, вот лог:

D, [2017-08-10T07:35:05.726316 #30605] DEBUG -- : Login
D, [2017-08-10T07:35:05.726420 #30605] DEBUG -- : {:phone_number=>"7919......", :phone_code_hash=>"ab7cfdd4......", :phone_code=>"....."}
D, [2017-08-10T07:35:05.733628 #30605] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/srv/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /srv/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://MYSITE/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%227919......%22%2C%22phone_code_hash%22%3A%22ab7cfdd4c9.........%22%2C%22phone_code%22%3A%.....%22%7D&command=Login"
D, [2017-08-10T07:35:07.985057 #30605] DEBUG -- : https://MYSITE/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%227919......%22%2C%22phone_code_hash%22%3A%22ab7cfdd4c......%22%2C%22phone_code%22%3A%.....%22%7D&command=Login
Push messaging is not supported.
[0.228] Api call auth.signIn
Error creating/accessing IndexedDB database [object Event]
   https://MYSITE/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
[0.623] Rpc error [object Object]
[0.627] Error 401 SESSION_PASSWORD_NEEDED false 2
   https://MYSITE/plugin_assets/redmine_telegram_common/webogram/js/app.js : 24
failed: {"code":401,"type":"SESSION_PASSWORD_NEEDED","description":"CODE#401 SESSION_PASSWORD_NEEDED","originalError":{"_":"rpc_error","error_code":401,"error_message":"SESSION_PASSWORD_NEEDED"},"input":"auth.signIn","stack":"empty stack"}

**Comment by andrich48** [comment]
У меня тоже проблема с авторизацией клиента.
Redmine 3.3.1, ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-linux], phantomjs 2.1.1.
Дополнительно установлена переменная окружения QT_QPA_PLATFORM=offscreen для phantomjs. Установил плагин на ветку master, затем обновил до develop.
Папка tmp/telegram_common отсутствовала, создал папку вручную.
При нажатии "Авторизовать клиент Telegram" страница повисает на неопределенный срок (>300 секунд).
При этом в логе log/telegram_common/telegram-cli.log появляются записи:

> D, [2017-08-15T13:25:35.937307 #1] DEBUG -- : Login
> D, [2017-08-15T13:25:35.937347 #1] DEBUG -- : {:phone_number=>"79214435736"}
> D, [2017-08-15T13:25:35.938167 #1] DEBUG -- : /usr/bin/phantomjs --local-storage-path="/usr/src/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "http://redmine5.c300.me/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279214435736%22%7D&command=Login"

Далее ничего не происходит, в логе ничего не пишется, код авторизации в телеграм не приходит, phantomjs висит в списке процессов.
Если руками запустить в консоли phantomjs с аналогичными параметрами, пишет вывод:

> root@88e9b938a4ee:/usr/src/redmine# sh -c '/usr/bin/phantomjs --local-storage-path="/usr/src/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "http://redmine5.c300.me/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279214435736%22%7D&command=Login"'
http://redmine5.c300.me/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279214435736%22%7D&command=Login
Push messaging is not supported.
[0.287]
performing idb upgrade from
[0.577]
[0.578]
[1.436]
[1.441]
[1.582]
[1.582]
[1.582]
[1.583]
[1.583]
[1.583]
[1.845]
[2.441]
[2.442]
[2.704]
success: {"_":"auth.sentCode","pFlags":{"phone_registered":true},"flags":3,"type":{"_":"auth.sentCodeTypeApp","length":5},"phone_code_hash":"1bde807ab85d0b8deb","next_type":{"_":"auth.codeTypeSms"}}
'waitFor()' finished in 3389ms.
Blocked a frame with origin "file://" from accessing a frame with origin "null".  The frame requesting access has a protocol of "file", the frame being accessed has a protocol of "about". Protocols must match.

В телеграм приходит код авторизации.
При этом на странице настроек плагина в Redmine никаких полей для ввода кода не появляется, по-прежнему предлагает ввести номер телефона.

**Comment by daos767** [comment]
root@lt2:/opt/redmine/redmine/log/telegram_common# /usr/local/bin/phantomjs --local-storage-path="/opt/redmine/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /opt/redmine/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "http://redmine.host/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%22380XXXXXXXXX%22%7D&command=Login"
http://redmine.host/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%22380XXXXXXXXX%22%7D&command=Login
Push messaging is not supported.
[0.073] Api call auth.sendCode
[0.479] Rpc response auth.sentCode
success: {"_":"auth.sentCode","pFlags":{"phone_registered":true},"flags":3,"type":{"_":"auth.sentCodeTypeApp","length":5},"phone_code_hash":"0c9f79c3fbd1353e8d","next_type":{"_":"auth.codeTypeSms"}}
'waitFor()' finished in 1000ms.

Когда отправляешь через командную строку то приходит на телефон код авторизации. Но из плагина пишет ошибку

**Comment by daos767** [comment]
Таки смог зарегистрировать.
Обновил redmine до версии 3.4.2.stable, потом грохнул плагин redmine_telegram_common и установил его снова.
Регистрация прошла даже из ветки master
Но только все равно не получается настроить отправку в телеграмм, но то уже другая история.

**Comment by andrich48** [comment]
Обновил redmine до версии 3.4.2, обновил ruby до версии 2.4, обновил плагин до ветки develop.
Хост с https.
Если запустить phantomjs руками из командной строки - все работает, код в телеграм приходит.
Если сбросить кеш и запросить регистрацию через Redmine - в логе log/telegram_common/telegram-cli.log появляется запись о запуске phantomjs и далее ничего не происходит, код авторизации не приходит.
Если откатить плагин обратно до ветки master, "Возникла ошибка при авторизации" пишется сразу, код в телеграм не приходит, лог выглядит так:

> D, [2017-08-17T13:25:13.535226 #1] DEBUG -- : Login
D, [2017-08-17T13:25:13.535285 #1] DEBUG -- : {:phone_number=>"79214435736"}
D, [2017-08-17T13:25:13.538004 #1] DEBUG -- : /usr/bin/phantomjs /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://redmine5.c300.me/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279214435736%22%7D&command=Login"
D, [2017-08-17T13:25:23.644765 #1] DEBUG -- : https://redmine5.c300.me/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279214435736%22%7D&command=Login
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
ReferenceError: Can't find variable: $
Blocked a frame with origin "file://" from accessing a frame with origin "null".  The frame requesting access has a protocol of "file", the frame being accessed has a protocol of "about". Protocols must match.

**Comment by shootkeen** [comment]
Установил плагин, пытаюсь авторизоваться через веб интерфейс плагина, вижу эту ошибку в production.log:

Processing by RedmineTelegramSetupController#step_2 as
 HTML                                                 
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"xxxxxxx==", "phone_number"=>"798
555xxxx"}                                            
  Current user: xxxxxx (id=6)                  
Failed to process API request                         
no implicit conversion of nil into String

Окружение:
Environment: Redmine version 3.4.2.stable.16962 Ruby version 2.2.4-p230 (2015-12-16) [x86_64-linux] Rails version 4.2.8 Environment production Database adapter Mysql2 SCM: Subversion 1.6.17 Git 1.7.10.4 Filesystem Redmine plugins: redmine_issue_completion 0.0.2 redmine_sidekiq 2.1.0 redmine_telegram_common 0.1.2


Redis установлен и запущен.

Помогите, пожалуйста, разобраться

**Comment by shootkeen** [comment]
А в веб интерфейсе ошибка: 

Возникла ошибка при авторизации

**Comment by olemskoi** [comment]
Здравствуйте.
Попробуйте начать с обновления ruby.

**Comment by shootkeen** [comment]
Спасибо за отклик. Обновил руби до 2.3, ошибка осталась в том же виде.

**Comment by shootkeen** [comment]
С ruby 2.4.0 ошибка не исчезла. В telegram-cli.log вывод такой:

-03T08:02:21.914443 #17677] DEBUG -- :  /var/www/sitename.ru/current/plugins/
redmine_telegram_common/config/phantom-proxy.js "http://sitename.ru/plugin_assets/redmin
e_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279855505300%22%7D&com
mand=Login"            
D, [2017-09-03T08:02:21.915578 #17677] DEBUG -- :

В веб интерфейсе по прежнему ошибка авторизации.

**Comment by shootkeen** [comment]
Все, успешно авторизовался, не был установлен PhantomJS.

**Comment by shootkeen** [comment]
Здравствуйте. Установил плагин telegram_chat. Все работает, но есть одна ошибка. Когда я создаю задачу через своего телеграмм бота, на последний вопрос "создать телеграмм чат?" я отвечаю "да". После этого шага ожидаемого создания телеграмм чата не происходит, появляется ошибка "команда не найдена".

В логе log/telegram_common/telegram-cli.log вижу такую  ошибку:

D, [2017-09-04T08:27:24.025134 #16061] DEBUG -- : http
s://sitename.ru/plugin_assets/redmine_telegram
_common/webogram/index.html#/api?args=<project_name>+900%22%2C%22<NameOfBot>%22%5D&
command=CreateChat                                    
Push messaging is not supported.                      
[0.134] Api call contacts.search                      
[0.526] Bad server salt [object Object]               
[0.670] Bad server salt [object Object]               
[0.822] Rpc error [object Object]                     
[0.823] Error 401 AUTH_KEY_UNREGISTERED false 2       
   https://sitename.ru/plugin_assets/redmine_t
elegram_common/webogram/js/app.js : 24                
[0.925] Api call auth.logOut                          
[1.233] Rpc response false                            
[1.260] Api call help.getNearestDc                    
Push messaging is not supported.                      
[0.044] Api call help.getNearestDc                    
[0.201] Bad server salt [object Object]               
[0.348] Bad server salt [object Object]               
[0.469] Rpc response nearestDc

Что бы это значило? Не подскажите? Заранее спасибо за помощь.

**Comment by radist** [comment]
tail -f log/telegram_common/telegram-cli.log

```
D, [2017-09-09T22:34:51.177730 #7485] DEBUG -- : Login
D, [2017-09-09T22:34:51.178115 #7485] DEBUG -- : {:phone_number=>"79281*******"}
D, [2017-09-09T22:34:51.200329 #7485] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/home/redmine/web/rm.******.ru/public_html/tmp/telegram_common" --ignore-ssl-errors=yes /home/redmine/web/rm.***********.ru/public_html/plugins/redmine_telegram_common/config/phantom-proxy.js "https://rm.*********.ru/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279281********%22%7D&command=Login"
D, [2017-09-09T22:35:02.552239 #7485] DEBUG -- : https://rm.*********.ru/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279281*********%22%7D&command=Login
```

Если выполнить в ручную то ни чего не происходит.

```
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
```

**Comment by constXife** [comment]
Создавайте, пожалуйста, отдельные задачи с проблемами, так как сейчас уже сложно разбираться в одной ветке обсуждения.

**Comment by constXife** [comment]
я вчера обновил плагин в ветке develop. У кого проблемы — обновите код плагина, перезагрузите redmine и убедитесь, чтобы на страницах настроек плагина везде стояло YES.

Yesterday I updated code in develop branch. Please, pull the changes, restart redmine, go to plugin settings page and make sure that all requirements are marked as YES.

**Comment by constXife** [comment]
Задачу пока закрываю. Если появятся проблемы — создавайте новую задачу.
