### ISSUE TITLE
Issue while running migrations

### ISSUE THREAD

**Issue by nixkn** [centosadmin/redmine_telegram_common#17]
Hello,

I am trying to install this plugin in order to setup the redmine_2fa as this is dependency plugin and im getting the error as below when running migrate command.

redmine - 3.3.4
ruby - 2.3

[pmkuwai@server redmine]$ bundle exec rake redmine:plugins:migrate RAILS_ENV=production
Migrating export_docx (Export DOCX)...
Migrating progressive_projects_list (Progressive Projects List plugin)...
Migrating redmine_agile (Redmine Agile plugin (Light version))...
Migrating redmine_checklists (Redmine Checklists plugin (Light version))...
Migrating redmine_lightbox2 (Redmine Lightbox 2)...
Migrating redmine_telegram_common (Redmine Telegram Common plugin)...
== 1 CreateTelegramCommonAccounts: migrating ==================================
-- create_table(:telegram_common_accounts)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: Cannot add foreign key constraint: ALTER TABLE `telegram_common_accounts` ADD CONSTRAINT `fk_rails_465d67b245`
FOREIGN KEY (`user_id`)
  REFERENCES `users` (`id`)
/home/pm/rails_apps/redmine/plugins/redmine_telegram_common/db/migrate/001_create_telegram_common_accounts.rb:3:in `change'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:453:in `migrate'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:466:in `each'
/home/pm/rails_apps/redmine/lib/redmine/plugin.rb:466:in `migrate'
/home/pm/rails_apps/redmine/lib/tasks/redmine.rake:127:in `block (3 levels) in <top (required)>'
/usr/local/bin/bundle:23:in `load'
/usr/local/bin/bundle:23:in `<main>'
A

**Comment by constXife** [comment]
@nixkn, hello!

May I ask you to show full log? As I see there is truncated log. I see error message, but don't see why it occur.

You can also revert plugin migrations and try to migrate again.

```bundle exec rake redmine:plugins:migrate NAME=redmine_telegram_common VERSION=0```

**Comment by constXife** [comment]
If you return, please, make new issue again.
