### ISSUE TITLE
Падает redmine после установки плагина

### ISSUE THREAD

**Issue by hatsnal** [centosadmin/redmine_telegram_common#18]
Перестал работать redmine после установки плагина и перезапуска apache.
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
Rails 4.2.8
phantomjs 2.1.1
redmine 3.4.2
OS CentOS 7.3
Надо ли что то править в самих файлах плагина после установки? 

bundle install и миграция проходят без ошибок. После перезапуска apache redmine падает в ошибку.

**Comment by hatsnal** [comment]
Вот лог https://pastebin.com/M5EqtUUJ

**Comment by constXife** [comment]
> bundle install и миграция проходят без ошибок. 

Покажите как выглядит ваш bundle install?

**Comment by constXife** [comment]
Если вернетесь — создайте, пожалуйста, задачу снова. Я пока закрою.
