### ISSUE TITLE
Ошибка авторизации. В логах нет ни каких подробностей.

### ISSUE THREAD

**Issue by radist** [centosadmin/redmine_telegram_common#19]
Ошибка авторизации. В логах нет ни каких подробностей.

tail -f log/telegram_common/telegram-cli.log

```
D, [2017-09-09T22:34:51.177730 #7485] DEBUG -- : Login
D, [2017-09-09T22:34:51.178115 #7485] DEBUG -- : {:phone_number=>"79281*******"}
D, [2017-09-09T22:34:51.200329 #7485] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/home/redmine/web/rm.******.ru/public_html/tmp/telegram_common" --ignore-ssl-errors=yes /home/redmine/web/rm.***********.ru/public_html/plugins/redmine_telegram_common/config/phantom-proxy.js "https://rm.*********.ru/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279281********%22%7D&command=Login"
D, [2017-09-09T22:35:02.552239 #7485] DEBUG -- : https://rm.*********.ru/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279281*********%22%7D&command=Login
```

Если выполнить в ручную то ни чего не происходит.

```
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               PostgreSQL
```
phantomjs установлен.
Пробовал и master и develop ветки. Куда копать?

**Comment by josemrh** [comment]
Hi, I have similar problem, this is my telegram-cli.log output

```
D, [2017-09-11T11:25:25.031202 #23685] DEBUG -- : Login
D, [2017-09-11T11:25:25.031300 #23685] DEBUG -- : {:phone_number=>"34XXXXXXXXX"}
D, [2017-09-11T11:25:25.034292 #23685] DEBUG -- : /usr/local/bin/phantomjs /home/redmine/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://XXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2234XXXXXXXXX%22%7D&command=Login"
D, [2017-09-11T11:25:35.425750 #23685] DEBUG -- : https://XXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2234XXXXXXXXX%22%7D&command=Login
Push messaging is not supported.
[0.098] Send req_pq 9db8ce9b2af3e80cb6d8125c3c91ead7
[5.491] Got ResPQ 4138d3c9bb6f3d4234518efc023a3dd1 1cf036f92c2eb32b 14101943622620965665
[5.492] PQ factorization start [object Uint8Array]
[8.562] PQ factorization done 60380
[8.571] Send req_DH_params
[8.726] Done decrypting answer
[8.727] Verifying DH params
[8.727] dhPrime cmp OK
[8.727] 1 < gA < dhPrime-1 OK
[8.727] 2^{2048-64} < gA < dhPrime-2^{2048-64} OK
[8.728] Apply server time 1505121933 1505121934025 -1 false
[9.255] Send set_client_DH_params
```
```
Environment:
  Redmine version                3.4.0.devel
  Ruby version                   2.4.0-p0 (2016-12-24) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
```

Thansk in advance

**Comment by ledorub-org** [comment]
Тоже при получении кода авторизации: 

/home/[dirname]/[sitename]/plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:3: syntax error, unexpected tLABEL def execute(command, config_path: nil, logger: nil, args: {}) ^ /home/[dirname]/[sitename]/plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:3: Can't assign to nil def execute(command, config_path: nil, logger: nil, args: {}) ^ /home/[dirname]/[sitename]/plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:3: Can't assign to nil def execute(command, config_path: nil, logger: nil, args: {}) ^ /home/[dirname]/[sitename]/plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:56: syntax error, unexpected tLABEL def log(message, operation: 'debug') ^ /home/[dirname]/[sitename]/plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:56: syntax error, unexpected ')', expecting keyword_end /home/[dirname]/[sitename]/plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:65: syntax error, unexpected keyword_end, expecting $end

**Comment by ledorub-org** [comment]
Такая же ошибка, как выше: "возникла ошибка авторизации" и никаких подробностей в логах.

**Comment by ledorub-org** [comment]
Кажется авторы уехали в отпуск. 

>https://rm.*********.ru/plugin_assets/redmine_telegram_common
Во первых проверьте: в новых версиях redmine, оказывается, - /**public**/plugin_assets/redmine_telegram_common. 
Урл захардкожен в одном из rb файлов (находится грепом).

Во вторых, что-то всё таки сломалось в webogram. Потому, что page.open в phantom_proxy.js выдаёт fail. Пробовал на http, на https. curl'ом всё отрабатывает нормально.

**Comment by constXife** [comment]
Прошу прощения, просто есть и другие дела + есть сложности в воспроизведении багов, о которых люди пишут, что не ускоряет процесс. 

Сейчас я готовлю больше диагностических операций и возможностей проверить корректно ли настроен связь с webogram. + я собираюсь выложить образ с docker, чтобы было проще посмотреть как работает плагин. Постараюсь это сделать к понедельнику.

**Comment by ledorub-org** [comment]
Хорошо. Я, к сожалению, столкнулся с обоими issue, которые у вас сейчас открыты - с этим и с тем, который в redmine_intouch. Не могу понять связаны они, или нет.

**Comment by constXife** [comment]
@ledorub-org, если сможете приготовить виртуалку для virtualbox с вашими настройками, то я мог бы посмотреть и помочь вам настроить. Один человек мне уже присылал виртуалку и я ему помог, заодно больше дало ясности почему у людей может ломаться плагин.

**Comment by ledorub-org** [comment]
@constXife написал вам в почту.

**Comment by constXife** [comment]
С проблемой у ledorub-org  разобрались. Проблема заключалась в том, что плагин не имел доступа до страницы плагина webogram, а phantomjs был устаревшей версии.

**Comment by constXife** [comment]
> Во первых проверьте: в новых версиях redmine, оказывается, - /public/plugin_assets/redmine_telegram_common.
Урл захардкожен в одном из rb файлов (находится грепом).

Хочу отметить для других, что тут изменять ничего не надо. Nginx в обычных настройках и так указывает на public.

**Comment by constXife** [comment]
@radist, проверьте доступность скрипта через браузер. По ссылке https://rm.*********.ru/plugin_assets/redmine_telegram_common/webogram/index.html у вас должна открыться страничка webogram.

**Comment by constXife** [comment]
@josemrh, please, make sure the page (https://XXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html) is accessible from browser and from your redmine server (via curl, for example).

**Comment by constXife** [comment]
Также, я вчера обновил плагин в ветке develop. У кого проблемы — обновите код плагина, перезагрузите redmine и убедитесь, чтобы на страницах настроек плагина везде стояло YES.

Yesterday I updated code in develop branch. Please, pull the changes, restart redmine, go to plugin settings page and make sure that all requirements are marked as YES.

**Comment by radist** [comment]
![ddddddd](https://user-images.githubusercontent.com/106756/30593678-24cd822e-9d54-11e7-8fb9-dd5007ae654a.png)

Что именно должно быть доступно? Урл открывается. Но там ни чего нет. Голубой экран. 

Вот код открывшейся страницы http://paste.org.ru/?xer56p

**Comment by olemskoi** [comment]
А покажите скриншот, пожалуйста.

**Comment by constXife** [comment]
Код страницы верный, но эта страничка должна быть доступна из редмайн. Попробуйте открыть эту страницу через curl сервера redmine.

Например, у меня так.

```
[redmine_server] $ curl https://site/plugin_assets/redmine_telegram_common/webogram/index.html

<!doctype html><html lang=en manifest=webogram.appcache ng-csp xmlns:ng=http://angularjs.org id=ng-app style="display: none;"><head><meta charset=utf-8><meta name=viewport content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"><title>Telegram Web</title><link rel=stylesheet href=css/app.css><link rel=manifest href=manifest.webapp.json><link rel=icon href=favicon.ico type=image/x-icon><link rel=apple-touch-icon href=img/iphone_home120.png><link rel=apple-touch-icon sizes=120x120 href=img/iphone_home120.png><link rel=apple-touch-startup-image media="(device-width: 320px)" href=img/iphone_startup.png><meta name=apple-mobile-web-app-title content="Telegram Web"><meta name=mobile-web-app-capable content=yes><meta name=apple-mobile-web-app-capable content=yes><meta name=apple-mobile-web-app-status-bar-style content=black-translucent><meta name=theme-color content=#497495><meta name=google content=notranslate><meta property=og:title content="Telegram Web"><meta property=og:url content="https://web.telegram.org/"><meta property=og:image content=https://web.telegram.org/img/logo_share.png><meta property=og:site_name content="Telegram Web"><meta property=og:description content="Welcome to the Web application of Telegram messenger. See https://github.com/zhukov/webogram for more info."></head><body><div class=page_wrap ng-view></div><div id=notify_sound></div><script src=js/app.js></script>
```

**Comment by ledorub-org** [comment]
У меня кстати страничка curl'ом прекрасно открывалась. Может тоже phantomjs старый?

**Comment by radist** [comment]
```
curl https://rm.*********.ru/plugin_assets/redmine_telegram_common/webogram/index.html
<!doctype html><html lang=en manifest=webogram.appcache ng-csp xmlns:ng=http://angularjs.org id=ng-app style="display: none;"><head><meta charset=utf-8><meta name=viewport content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"><title>Telegram Web</title><link rel=stylesheet href=css/app.css><link rel=manifest href=manifest.webapp.json><link rel=icon href=favicon.ico type=image/x-icon><link rel=apple-touch-icon href=img/iphone_home120.png><link rel=apple-touch-icon sizes=120x120 href=img/iphone_home120.png><link rel=apple-touch-startup-image media="(device-width: 320px)" href=img/iphone_startup.png><meta name=apple-mobile-web-app-title content="Telegram Web"><meta name=mobile-web-app-capable content=yes><meta name=apple-mobile-web-app-capable content=yes><meta name=apple-mobile-web-app-status-bar-style content=black-translucent><meta name=theme-color content=#497495><meta name=google content=notranslate><meta property=og:title content="Telegram Web"><meta property=og:url content="https://web.telegram.org/"><meta property=og:image content=https://web.telegram.org/img/logo_share.png><meta property=og:site_name content="Telegram Web"><meta property=og:description content="Welcome to the Web application of Telegram messenger. See https://github.com/zhukov/webogram for more info."></head><body><div class=page_wrap ng-view></div><div id=notify_sound></div><script src=js/app.js></script></body></html>
```

**Comment by radist** [comment]
phantomjs - 2.1.1

**Comment by ledorub-org** [comment]
попробуйте 2.2?

**Comment by radist** [comment]
![image](https://user-images.githubusercontent.com/106756/30594585-31e10b68-9d57-11e7-8a49-d8d496bdaf1c.png)
скриншот

**Comment by radist** [comment]
Где взять 2.2 ? http://phantomjs.org/download.html

**Comment by constXife** [comment]
У меня ваш скриншот выглядит как однородная серая область. Так и должно быть?

**Comment by ledorub-org** [comment]
Сорри, это мой глюк. У меня тоже 2.1.1

**Comment by radist** [comment]
> У меня ваш скриншот выглядит как однородная серая область. Так и должно быть?

Да, там ни чего нет. Однородная серо голубая область.

**Comment by constXife** [comment]
Убедитесь, что у вас все файлы оригинальные и вы заходите на неё достаточно современным браузером.

Должно выглядеть так.

<img width="1261" alt="2017-09-19 20 10 02" src="https://user-images.githubusercontent.com/870327/30594808-93099906-9d79-11e7-955c-306a1060effa.png">

**Comment by radist** [comment]
plugin_assets/redmine_telegram_common/webogram/webogram.appcache - Page not found
```

$ cat public/plugin_assets/redmine_telegram_common/webogram/webogram.appcache 
CACHE MANIFEST
# Time: Tue Jul 25 2017 01:02:27 GMT+0700 (+07)


CACHE:
favicon.ico
favicon_unread.ico
service_worker.js
css/app.css
css/desktop.css
css/mobile.css
img/Manytabs.png
img/Manytabs_2x.png
img/Telegram.png
img/Telegram.svg
img/Telegram72.png
img/Telegram72_2x.png
img/Telegram_2x.png
img/blank.gif
img/emojisprite_0.png
img/emojisprite_1.png
img/emojisprite_2.png
img/emojisprite_3.png
img/emojisprite_4.png
img/iphone_home120.png
img/iphone_startup.png
img/logo_share.png
img/sound_a.mp3
js/app.js
nacl/mtproto_crypto.nmf
nacl/mtproto_crypto.pexe
img/changelog/card_wecandoit.png
img/placeholders/DialogListAvatarSystem@2x.png
img/placeholders/GroupAvatar1@2x.png
img/placeholders/GroupAvatar2@2x.png
img/placeholders/GroupAvatar3@2x.png
img/placeholders/GroupAvatar4@2x.png
img/placeholders/PhotoThumbConversation.gif
img/placeholders/PhotoThumbModal.gif
img/placeholders/UserAvatar1@2x.png
img/placeholders/UserAvatar2@2x.png
img/placeholders/UserAvatar3@2x.png
img/placeholders/UserAvatar4@2x.png
img/placeholders/UserAvatar5@2x.png
img/placeholders/UserAvatar6@2x.png
img/placeholders/UserAvatar7@2x.png
img/placeholders/UserAvatar8@2x.png
img/placeholders/VideoThumbConversation.gif
img/placeholders/VideoThumbModal.gif
js/lib/bin_utils.js
js/lib/crypto_worker.js
js/lib/polyfill.js
js/lib/push_worker.js
img/icons/AboutLogos.png
img/icons/AboutLogos_2x.png
img/icons/General.png
img/icons/General_2x.png
img/icons/IconsetSmiles.png
img/icons/IconsetSmiles_2x.png
img/icons/IconsetW.png
img/icons/IconsetW_2x.png
img/icons/Major.png
img/icons/Major_2x.png
img/icons/MobileIcons.png
img/icons/MobileIcons_2x.png
img/icons/PhotoIcons.png
img/icons/PhotoIcons_2x.png
img/icons/ProfileIcons.png
img/icons/ProfileIcons_2x.png
img/icons/icon.svg
js/locales/de-de.json
js/locales/en-us.json
js/locales/es-es.json
js/locales/it-it.json
js/locales/nl-nl.json
js/locales/pt-br.json
js/locales/ru-ru.json
vendor/closure/long.js
vendor/cryptoJS/crypto.js
vendor/jsbn/jsbn_combined.js
vendor/leemon_bigint/bigint.js
vendor/rusha/rusha.js
vendor/angular/i18n/angular-locale_de-de.js
vendor/angular/i18n/angular-locale_en-us.js
vendor/angular/i18n/angular-locale_es-es.js
vendor/angular/i18n/angular-locale_it-it.js
vendor/angular/i18n/angular-locale_nl-nl.js
vendor/angular/i18n/angular-locale_pt-br.js
vendor/angular/i18n/angular-locale_ru-ru.js


NETWORK:
http://*
https://*

```

**Comment by radist** [comment]
> Убедитесь, что у вас все файлы оригинальные и вы заходите на неё достаточно современным браузером.

Хром последней версии. На счет файлов не понял. Что должно быть оригинальным?

**Comment by constXife** [comment]
У вас выглядит так же?

constXife @ constXife ~ % cd /var/www/redmine/plugins/redmine_telegram_common

constXife @ constXife ~ % git status                                                                                                                                                                 
On branch develop
Your branch is up-to-date with 'origin/develop'.
nothing to commit, working tree clean

**Comment by radist** [comment]
Я нашел причину. Пришлось дописать в конфиг nginx pexe|nmf|json|appcache для отдачи как статики. Иначе оно переправлялось на бекенд который отдавал 404

**Comment by constXife** [comment]
@radist, сообщите, пожалуйста, если вам удастся настроить плагин, чтобы мы могли закрыть эту задачу.

**Comment by radist** [comment]
Все заработало. Авторизоваться удалось. webogram не работал, так как часть скриптов отдавало - 404. nginx не считал файлы pexe nmf json appcache статикой и отправлял запрос на бекенд. Который отдавал 404.

**Comment by constXife** [comment]
@radist, вот и славно, что всё получилось. Обращайтесь, если возникнут новые проблемы. 

@josemrh, I will close this issue. If your problem still exists, please, make new issue.
