### ISSUE TITLE
Плагин не устанавливается / не видит системных требований

### ISSUE THREAD

**Issue by andrich48** [centosadmin/redmine_telegram_common#20]
Redmine 3.4.2, ruby 2.4.1p111, PhantomJS 2.1.1
Плагин обновил до последней версии ветки develop.
В redmine выключил HTTPS, только HTTP.
На странице конфигурации плагина таблица:
> 
> PhantomJS | Yes | Обновите вашу версию PhantomJS до ~> 2.1 (сейчас: 2.1.1)
> Webogram | No | Убедитесь, что URL webogram (сейчас:  http://XXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html)  доступен с вашего сервера redmine
> Rails Env | Yes | Убедитесь, что ваш RAILS_ENV — production (сейчас: production)

Указанный URL по факту доступен с сервера redmine, проверял через curl.

> root@8d1efa552d13:/tmp# sudo -u redmine curl http://XXXXX/plugin_assets/redmine_telegram_common/webogram/index.html
> <!doctype html><html lang=en manifest=webogram.appcache ng-csp xmlns:ng=http://angularjs.org id=ng-app(...) 

В логе /usr/src/redmine/log/telegram_common/telegram-cli.log при открытии страницы конфигурации плагина появляются записи:

> D, [2017-09-21T09:20:33.274827 #1] DEBUG -- : Test
> D, [2017-09-21T09:20:33.274918 #1] DEBUG -- : {}
> D, [2017-09-21T09:20:33.275543 #1] DEBUG -- : /usr/bin/phantomjs --local-storage-path="/usr/src/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "http://XXXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"
> D, [2017-09-21T09:22:42.447869 #1] DEBUG -- : Test
> D, [2017-09-21T09:22:42.447986 #1] DEBUG -- : {}
> D, [2017-09-21T09:22:42.449865 #1] DEBUG -- : /usr/bin/phantomjs --local-storage-path="/usr/src/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "http://XXXXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"

Более ничего не появляется. При этом, в домашней папке пользователя redmine каждый раз заново создается папка:
~/.local/share/Ofi Labs/PhantomJS/http_XXXXX_0.indexeddb.leveldb
Что говорит о том что PhantomJS вроде как запускается успешно. В логе хттп-сервера записи от PhantomJS есть.

Если руками запустить phantomjs с аналогичными параметрами то результат такой:

> 
> root@8d1efa552d13:/tmp# sudo -u redmine /usr/bin/phantomjs --local-storage-path="/usr/src/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "http://XXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"
> http://XXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
> Push messaging is not supported.
> success: api test
> performing idb upgrade from
> 'waitFor()' finished in 1002ms.
> Blocked a frame with origin "file://" from accessing a frame with origin "null".  The frame requesting access has a protocol of "file", the frame being accessed has a protocol of "about". Protocols must match.

**Comment by olemskoi** [comment]
Попробуйте наоборот - включить https.

**Comment by andrich48** [comment]
Включил https в настройках redmine. Не помогло, на странице настроек плагина результат аналогичный:

> PhantomJS | Yes | Обновите вашу версию PhantomJS до ~> 2.1 (сейчас: 2.1.1)
Webogram | No | Убедитесь, что URL webogram (сейчас:  https://XXXXX/plugin_assets/redmine_telegram_common/webogram/index.html)  доступен с вашего сервера redmine
Rails Env | Yes | Убедитесь, что ваш RAILS_ENV — production (сейчас: production)

В логе telegram-cli.log появляются записи:
> D, [2017-09-21T14:43:11.701605 #1] DEBUG -- : Test
> D, [2017-09-21T14:43:11.747395 #1] DEBUG -- : {}
> D, [2017-09-21T14:43:11.748231 #1] DEBUG -- : /usr/bin/phantomjs --local-storage-path="/usr/src/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://XXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"

В логе http-сервера появляется много новых записей с агентом PhantomJS.

В консоли - вроде работает:

> root@8d1efa552d13:/tmp# sudo -u redmine sh
$ sh -c '/usr/bin/phantomjs --local-storage-path="/usr/src/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://XXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"'
https://XXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
Push messaging is not supported.
success: api test
performing idb upgrade from
'waitFor()' finished in 1001ms.
Blocked a frame with origin "file://" from accessing a frame with origin "null".  The frame requesting access has a protocol of "file", the frame being accessed has a protocol of "about". Protocols must match.

**Comment by constXife** [comment]
В консоли и правда выглядит как будто бы работает. Вы уверены, что руками и через "redmine" работают через одного пользователя? Или быть может какие-то не все нужные окружения доступны? Я добавлю в вывод логов whoami, чтобы было проще разобраться.

**Comment by constXife** [comment]
Обновите плагин из develop ветки. В логах теперь будет также появляться whoami для упрощения отладки. Может это поможет нам выяснить в чём проблема.

**Comment by andrich48** [comment]
Плагин обновил.
Страница с настройками выглядит по-прежнему:

> PhantomJS | Yes | Обновите вашу версию PhantomJS до ~> 2.1 (сейчас: 2.1.1)
> -- | -- | --
> Webogram | No | Убедитесь, что URL webogram (сейчас:  https://XXXXXXXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html)  доступен с вашего сервера redmine
> Rails Env | Yes | Убедитесь, что ваш RAILS_ENV — production (сейчас: production)

При обновлении страницы в логе telegram-cli.log появляются записи:

> D, [2017-09-22T08:30:09.963469 #1] DEBUG -- : whoami: redmine
> 
> D, [2017-09-22T08:30:09.963520 #1] DEBUG -- : Test
> D, [2017-09-22T08:30:09.963536 #1] DEBUG -- : {}
> D, [2017-09-22T08:30:09.964156 #1] DEBUG -- : /usr/bin/phantomjs --local-storage-path="/usr/src/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://XXXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"

Если это поможет, то было обнаружено что /usr/bin/phantomjs это обычный враппер для /usr/bin/phantomjs/phantomjs, поэтому я немного поправил враппер и добавил в него еще немного отладочного вывода:

> root@8d1efa552d13:/usr/bin# cat /usr/bin/phantomjs 
> #!/bin/sh
> LD_LIBRARY_PATH="/usr/lib/phantomjs:$LD_LIBRARY_PATH"
> export LD_LIBRARY_PATH
> export QT_QPA_PLATFORM=offscreen
> echo $@ > /tmp/phantomjs.log
> exec "/usr/lib/phantomjs/phantomjs" "$@" 2>&1 | tee /tmp/phantomjs.log
> env >> /tmp/phantomjs.log

Т.е. вся командная строка и переменные окружения записываются в дополнительный отладочный лог прямо в момент вызова phantomjs.
Дополнительный отладочный лог в момент обновления параметров плагина через браузер выглядит так (логин-пароли замазал):

> root@8d1efa552d13:/tmp# cat /tmp/phantomjs.broken.log 
> https://XXXXXXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
> Push messaging is not supported.
> success: api test
> performing idb upgrade from
> 'waitFor()' finished in 1012ms.
> Blocked a frame with origin "file://" from accessing a frame with origin "null".  The frame requesting access has a protocol of "file", the frame being accessed has a protocol of "about". Protocols must match.
> 
> RUBY_MAJOR=2.4
> REDMINE_SECRET_KEY_BASE=
> BUNDLER_VERSION=1.15.3
> HOSTNAME=8d1efa552d13
> RUBYGEMS_VERSION=2.6.12
> SHLVL=0
> RUBYOPT=-rbundler/setup
> LD_LIBRARY_PATH=/usr/lib/phantomjs:
> HOME=/home/redmine
> REDMINE_DOWNLOAD_MD5=2980b80e9acc81c01c06adb86eb4f37d
> REDMINE_DB_PASSWORD=XXXXXXXX
> POSTGRES_ENV_PG_VERSION=9.5.7-1.pgdg80+1
> POSTGRES_ENV_LANG=en_US.utf8
> BUNDLE_APP_CONFIG=/usr/local/bundle
> REDMINE_DB_USER=XXXXXXXXXX
> REDMINE_DB_POSTGRES=XXXXXXXXXXXXX
> BUNDLE_BIN=/usr/local/bundle/bin
> REDMINE_VERSION=3.4.2
> RUBYLIB=/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/lib
> RUBY_VERSION=2.4.1
> TERM=xterm
> POSTGRES_ENV_REDMINE_DB_PASSWORD=XXXXXXXXXXXXX
> RACK_ENV=production
> PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> POSTGRES_ENV_GOSU_VERSION=1.7
> POSTGRES_PORT_5432_TCP_ADDR=172.17.0.2
> POSTGRES_ENV_REDMINE_DB_USER=XXXXXXXXXXXX
> BUNDLE_PATH=/usr/local/bundle
> POSTGRES_ENV_REDMINE_DB_POSTGRES=XXXXXXXXXXXX
> BUNDLE_BIN_PATH=/usr/local/lib/ruby/gems/2.4.0/gems/bundler-1.15.3/exe/bundle
> POSTGRES_PORT_5432_TCP_PORT=5432
> POSTGRES_PORT_5432_TCP_PROTO=tcp
> REDMINE_DB_DATABASE=XXXXXXXXXXXXXX
> GEM_HOME=/usr/local/bundle
> POSTGRES_PORT=tcp://172.17.0.2:5432
> RAILS_ENV=production
> BUNDLE_GEMFILE=/usr/src/redmine/Gemfile
> POSTGRES_ENV_PG_MAJOR=9.5
> RUBY_DOWNLOAD_SHA256=4fc8a9992de3e90191de369270ea4b6c1b171b7941743614cc50822ddc1fe654
> GOSU_VERSION=1.7
> PWD=/usr/src/redmine
> QT_QPA_PLATFORM=offscreen
> POSTGRES_NAME=/nredmine342/postgres
> POSTGRES_PORT_5432_TCP=tcp://172.17.0.2:5432
> GEM_PATH=
> POSTGRES_ENV_REDMINE_DB_DATABASE=XXXXXXXXXXXXXXX
> TINI_VERSION=v0.9.0
> BUNDLE_SILENCE_ROOT_WARNING=1
> BUNDLER_ORIG_PATH=/usr/local/bundle/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> POSTGRES_ENV_PGDATA=/var/lib/postgresql/data

Если попробовать запустить phantomjs вручную:

> root@8d1efa552d13:/tmp# sudo -u redmine sh
> $ sh -c '/usr/bin/phantomjs --local-storage-path="/usr/src/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://XXXXXXXXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"'
> https://XXXXXXXXXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
> Push messaging is not supported.
> success: api test
> performing idb upgrade from
> 'waitFor()' finished in 1010ms.
> Blocked a frame with origin "file://" from accessing a frame with origin "null".  The frame requesting access has a protocol of "file", the frame being accessed has a protocol of "about". Protocols must match.
> 
> $ exit

То отладочный лог выглядит так:

> root@8d1efa552d13:/tmp# cat /tmp/phantomjs.log 
> https://XXXXXXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
> Push messaging is not supported.
> success: api test
> performing idb upgrade from
> 'waitFor()' finished in 1010ms.
> Blocked a frame with origin "file://" from accessing a frame with origin "null".  The frame requesting access has a protocol of "file", the frame being accessed has a protocol of "about". Protocols must match.
> 
> SUDO_GID=0
> MAIL=/var/mail/redmine
> USER=redmine
> HOSTNAME=8d1efa552d13
> LD_LIBRARY_PATH=/usr/lib/phantomjs:
> HOME=/home/redmine
> SUDO_UID=0
> LOGNAME=redmine
> TERM=xterm
> USERNAME=redmine
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> SUDO_COMMAND=/bin/sh
> SHELL=/bin/sh
> SUDO_USER=root
> PWD=/tmp
> QT_QPA_PLATFORM=offscreen

В логе хттп-сервера в обоих случаях появляется множество запросов от PhantomJS, есть ли разница - не проверял.

**Comment by andrich48** [comment]
Еще добавлю, в develop-версии плагина есть Docker файл, дык если собрать образ докера целиком из Dockerfile и попробовать запустить то результаты аналогичные - не видит Webogram :)
В консоли изначально вроде не заработало:

> root@0bb2f0f62ebb:/# su redmine
> $ whoami
> redmine
> $ /usr/local/bin/phantomjs --local-storage-path="/usr/src/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://XXXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"
> https://XXXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
> Push messaging is not supported.
> success: api test
> Error creating/accessing IndexedDB database [object Event]
>    https://XXXXXXX/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
> 'waitFor()' finished in 1006ms.
> $ exit

Создаем папку /home/redmine, назначаем права chown redmine:redmine /home/redmine, пробуем еще раз:

> root@0bb2f0f62ebb:/# su redmine
> $ /usr/local/bin/phantomjs --local-storage-path="/usr/src/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://XXXXXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"
> https://XXXXXXXXX/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
> Push messaging is not supported.
> success: api test
> performing idb upgrade from 0 to 2
> 'waitFor()' finished in 1012ms.
> $

Вроде работает, а в параметрах плагина по-прежнему пишет Webogram no.

**Comment by constXife** [comment]
Вы не могли бы сделать виртуалку с текущим окружением, чтобы я мог поразбираться вручную? Мне пока так сложно что-то сказать. Я правда ещё толком не тестировал работу плагина с ruby 2.4. Попробую протестировать.

**Comment by andrich48** [comment]
Последовательность действий для воспроизведения:
1. Ставим Debian stretch
2. Согласно оф инструкции докера ставим docker-ce
3. Клонируем плагин и создаем docker-образ redmine из Docker-файла ветки develop:
docker build -t redmine243_tc_ruby24 .
3. Запускаем postgres и создаем пользователя и БД (docker run --name postgres postgres:9.5)
4. Запускаем redmine из созданного образа
docker run -ti --name r243_tc_r24 -e REDMINE_DB_POSTGRES=postgres -e REDMINE_DB_DATABASE=udb -e REDMINE_DB_PASSWORD=password -e REDMINE_DB_USER=uname -p 3000:3000 --link postgres:postgres redmine243_tc_ruby24
5. При необходимости настраиваем контейнер - прописываем ип-адрес хоста в /etc/hosts с адресом например redmine.my
6. Заходим на сайт redmine.my:3000, проверяем модуль и Webogram.

Известные глюки - иногда при отладке плагин начинает работать как надо и докладывает о доступности Webogram. К сожалению, причину выявить не удалось и удачные действия повторить не удалось. Решение - удалить докер-контейнер (docker rm r243_tc_r24) и создать его заново, плагин снова не работает.

Создал ВМ в VirtualBox и экспортировал, скачать можно тут:
https://drive.google.com/file/d/0ByS3L7XkJpikY05URWt1UlIzeDA/view?usp=sharing
Размер 2Гб.
Пользователь user, пароль userpassword, пользователь root, пароль rootpassword, после старта ВМ надо запустить все docker-контейнеры и настроить /etc/hosts вручную. Логин редмайна admin пароль adminpassword

**Comment by constXife** [comment]
Спасибо за обстоятельный ответ! В ближайшее время займемся.

**Comment by constXife** [comment]
Добрый день. Спасибо, что нашли время сделать виртуальный образ.

1. Хочу отметить, что наш Dockerfile пока не готов для корректной работы, он попал в develop по недосмотру. Я его уже убрал с develop.
2. Откровенно говоря, я ожидал, что вы в виртуалке разместите архитектуру вашего продакшена, а не наш нерабочий образ docker. 

Схема работы плагина такая. 

Во-первых, для нормальной работы в production нужен отдельный сервер для раздачи статики типа Passenger или Nginx. Обычно Rails как раз используют в связке с nginx или passenger. (В нашем докере как раз проблема в том, что не настроена до конца связка с passenger)

Во-вторых, если вы используете виртуализацию, убедитесь что вы делаете ручные проверки на доступность webogram именно изнутри контейнера, а не из хоста. Работа плагина достаточно прозрачна — плагин вызывает phantomjs, который отправляет запрос на страницу webogram. 

В-третьих, наш плагин рассчитан на работу в корректно настроенной, среднестатистической среде Redmine. Возможно, у вас в инфраструктуре есть какие-то особенные правила обработки запросов Nginx, может какие-то особенные правила фаервола, может быть что угодно. Вполне может что наш код плагина что-то непредусматривает. Но, к сожалению, я не могу диагностировать проблему, не видя систему.

Если желаете, я могу также сделать виртуальный образ с рабочим redmine + redmine_telegram_common, но позже. Сейчас не имею возможности.

**Comment by andrich48** [comment]
1. Архитектура продакшена на данный момент неактуальна т.к. у меня в принципе не получается запустить этот плагин даже на чистом redmine в тепличных условиях (в docker).
2. Docker использовался т.к. чистый Redmine вполне нормально запускается в docker (только на rails, без nginx). До сих пор лично я проблем с плагинами в Docker не замечал, с использованием стандартного redmine из docker hub.
3. Если плагин категорически несовместим с Rails и требует "среднестатистической среды Redmine" (отдельного сервера для статики) то этот пункт можно вынести в системные требования. Это есть в описании но это неочевидно, я с первого раза проглядел.
4. Все проверялось изнутри контейнера, без специальных настроек, с идентичными правами и переменными окружения, я там разве что с лупой не стоял и не смотрел strace/ltrace.
5. Попробую повторить эксперимент с nginx, о результатах отпишусь

**Comment by constXife** [comment]
> Если плагин категорически несовместим с Rails и требует "среднестатистической среды Redmine" (отдельного сервера для статики)

Прокомментирую в том числе и для других пользователей. Запускать Rails-приложение в режиме эксплуатации не под отдельным сервером статики абсолютно не рекомендуется официальной документацией.

> config.serve_static_files configures Rails itself to serve static files. Defaults to true, but in the production environment is turned off as the server software (e.g. NGINX or Apache) used to run the application should serve static assets instead. Unlike the default setting set this to true when running (absolutely not recommended!) or testing your app in production mode using WEBrick. Otherwise you won't be able use page caching and requests for files that exist regularly under the public directory will anyway hit your Rails app.
http://guides.rubyonrails.org/v4.2/configuring.html

Голый Rails-сервер используют для разработки и в рамках разработки имеются средства, чтобы запускать необходимые файлы без nginx — это посредством отдельного процесса gulp и этот момент указан также в README в соответствующей секции Plugin development.

**Comment by andrich48** [comment]
Спасибо, проблема решилась.
Удалось добиться работоспособности в следующих условиях:
Debian stretch, стандартный пакет redmine + redmine-pgsql, apache2, libapache2-mod-passenger, phantomjs.
  Redmine version                3.3.1.stable
  Ruby version                   2.3.3-p222 (2016-11-21) [x86_64-linux-gnu]
Версия плагина redmine_telegram_common 0.1.3.
Кому интересно, инструкция: 
1. ставим debian и redmine как обычно из стандартных пакетов (можно воспользоваться инструкцией для установки на ubuntu 12.04 с сайта redmine)
2. Допиливаем apache2/mods_enabled/passenger.conf (PassengerDefaultUser www-data), PhantomJS для запуска без ГУИ (export QT_QPA_PLATFORM=offscreen)
3. Допиливаем алиас: /redmine/plugin_assets -> /usr/share/redmine/public/plugin_assets/
4. Ставим плагин по оф. инструкции - все работает, необходимые системные требования видит, код авторизации приходит и регистрируется успешно.

**Comment by constXife** [comment]
Спасибо, что отписались!
