### ISSUE TITLE
После установки плагина при переходе в  настройки редмайн сообщает об ошибке

### ISSUE THREAD

**Issue by esuslik** [centosadmin/redmine_telegram_common#22]
В логах
Completed 500 Internal Server Error in 275ms (ActiveRecord: 52.2ms)

ActionView::Template::Error (undefined method `strip' for nil:NilClass):
    24:   <tr>
    25:     <td>PhantomJS</td>
    26:     <td>
    27:       <% if telegram.phantomjs_version_valid? %>
    28:       <%= t 'telegram_common.requirements.yes' %>
    29:       <% else %>
    30:       <%= t 'telegram_common.requirements.no' %>
  plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:49:in `phantomjs'
  plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:45:in `phantomjs_version'
  plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:33:in `phantomjs_version_valid?'
  plugins/redmine_telegram_common/app/views/settings/_telegram_common.html.erb:27:in `_plugins_redmine_telegram_common_app_views_settings__telegram_common_html_erb__4496176620500294119_80705540'
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__3810874116462357486_54176480'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb__3810874116462357486_54176480'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by relige** [comment]
Поставил по инструкции. Redmine отдает 500 при попытке зайти в настройки плагина.
В логах:

`ActionView::Template::Error (undefined method `strip' for nil:NilClass):
    24:   <tr>
    25:     <td>PhantomJS</td>
    26:     <td>
    27:       <% if telegram.phantomjs_version_valid? %>
    28:       <%= t 'telegram_common.requirements.yes' %>
    29:       <% else %>
    30:       <%= t 'telegram_common.requirements.no' %>
  plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:49:in `phantomjs'
  plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:45:in `phantomjs_version'
  plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:33:in `phantomjs_version_valid?'
  plugins/redmine_telegram_common/app/views/settings/_telegram_common.html.erb:27:in `_plugins_redmine_telegram_common_app_views_settings__telegram_common_html_erb___2757408174892566693_48551940'
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb___2292001673985875011_43092640'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb___2292001673985875011_43092640'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'`

**Comment by tarasius** [comment]
Аналогичная ошибка. Редмайн запущен из докер контейнера, плагин установил в контейнере.
В списке плагинов появился, но при попытке зайти в настройки - ошибка. Логи:

> Started GET "/settings/plugin/redmine_telegram_common" for 88.73.20.159 at 2017-11-18 12:34:27 +0000
> Processing by SettingsController#plugin as HTML
>   Parameters: {"id"=>"redmine_telegram_common"}
>   Current user: admin (id=1)
>   Rendered plugins/redmine_telegram_common/app/views/settings/_telegram_common.html.erb (4.5ms)
>   Rendered settings/plugin.html.erb within layouts/admin (5.5ms)
> Completed 500 Internal Server Error in 18ms (ActiveRecord: 5.1ms)
> 
> ActionView::Template::Error (undefined method `strip' for nil:NilClass):
>     24:   <tr>
>     25:     <td>PhantomJS</td>
>     26:     <td>
>     27:       <% if telegram.phantomjs_version_valid? %>
>     28:       <%= t 'telegram_common.requirements.yes' %>
>     29:       <% else %>
>     30:       <%= t 'telegram_common.requirements.no' %>
>   plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:45:in `phantomjs_version'
>   plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:33:in `phantomjs_version_valid?'
>   plugins/redmine_telegram_common/app/views/settings/_telegram_common.html.erb:27:in `_plugins_redmine_telegram_common_app_views_settings__telegram_common_html_erb__354349020945187156_70343995399260'
>   app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb__1476451550947315973_70343995365460'
>   app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb__1476451550947315973_70343995365460'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'
>

**Comment by nedden** [comment]
Нужно установить PhantomJS

**Comment by tarasius** [comment]
Спасибо, установил, но не особо помогло. В настройках плагина **Webogram | No**
Когда открываю страницу Webogram по указанному урлу, всё работает.
Дальше полез в логи:

```
D, [2017-11-19T15:38:40.978746 #1] DEBUG -- : whoami: redmine
D, [2017-11-19T15:38:40.979132 #1] DEBUG -- : Test
D, [2017-11-19T15:38:40.979193 #1] DEBUG -- : {}
D, [2017-11-19T15:38:40.980782 #1] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/usr/src/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "http://localhost:3000/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"
```
Дальше пусто.

Когда логинюсь в консоль докер контейнера как рут, то все команды phantomjs проходят. И код получаю на смс. Но так как whoami: redmine, попробовал зайти в консоль юзером redmine.

```
/usr/local/bin/phantomjs --local-storage-path="/usr/src/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/src/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "http://localhost:3000/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"
http://localhost:3000/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
Push messaging is not supported.
success: api test
```
**Error creating/accessing IndexedDB database [object Event]**
```
http://localhost:3000/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
'waitFor()' finished in 1000ms.
```
Такое ощущение, что что-то с правами, только не пойму что именно

**Comment by wiifit** [comment]
Появляется аналогичная ошибка при установленном PhantomJS 2.1.1.
Redmine запускается c использованием Passenger от пользователя www-data. Плагин установлен также под данным пользователем
```
Started GET "/settings/plugin/redmine_telegram_common" for 10.0.2.2 at 2017-11-27 15:45:09 +0000
Processing by SettingsController#plugin as HTML
  Parameters: {"id"=>"redmine_telegram_common"}
  Current user: admin (id=1)
  Rendered plugins/redmine_telegram_common/app/views/settings/_telegram_common.html.erb (4.6ms)
  Rendered settings/plugin.html.erb within layouts/admin (5.7ms)
Completed 500 Internal Server Error in 24ms (ActiveRecord: 3.8ms)

ActionView::Template::Error (undefined method `strip' for nil:NilClass):
    24:   <tr>
    25:     <td>PhantomJS</td>
    26:     <td>
    27:       <% if telegram.phantomjs_version_valid? %>
    28:       <%= t 'telegram_common.requirements.yes' %>
    29:       <% else %>
    30:       <%= t 'telegram_common.requirements.no' %>
  plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:49:in `phantomjs'
  plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:45:in `phantomjs_version'
  plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:33:in `phantomjs_version_valid?'
  plugins/redmine_telegram_common/app/views/settings/_telegram_common.html.erb:27:in `_plugins_redmine_telegram_common_app_views_settings__telegram_common_html_erb__1895105096181581140_47447457523200'
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb___1809811401479238033_47447456910940'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb___1809811401479238033_47447456910940'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```
В чем может быть причина?

**Comment by constXife** [comment]
@wiifit, добрый день, прошу за долгую задержку в ответе.

Судя по ошибке, у вас phantomjs не виден редмайну в системе. Попробуйте самостоятельно в консоли выполнить команду which phantomjs и она должна вернуть путь к программе.

def phantomjs_version
   `#{phantomjs} -v`.strip
end

def phantomjs
   `which phantomjs`.strip
end

Какая у вас операционная система?

**Comment by wiifit** [comment]
@constXife  добрый день.
команда `which phantomjs` возвращает следующее:
`/usr/bin/phantomjs`
Версия ОС: Ununtu 16.04 LTS

**Comment by esuslik** [comment]
Полностью установил все на новый сервер.
redmine 3.4 postgresql
Плагины поставил все по новой. Ошибка таже 500
ActionView::Template::Error (undefined method `strip' for nil:NilClass):
    24:   <tr>
    25:     <td>PhantomJS</td>
    26:     <td>
    27:       <% if telegram.phantomjs_version_valid? %>
    28:       <%= t 'telegram_common.requirements.yes' %>
    29:       <% else %>
    30:       <%= t 'telegram_common.requirements.no' %>
  plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:49:in `phantomjs'
  plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:45:in `phantomjs_version'
  plugins/redmine_telegram_common/lib/telegram_common/telegram.rb:33:in `phantomjs_version_valid?'
  plugins/redmine_telegram_common/app/views/settings/_telegram_common.html.erb:27:in `_plugins_redmine_telegram_common_app_views_settings__telegram_common_html_erb__1895105096181581140_47447457523200'
  app/views/settings/plugin.html.erb:6:in `block in _app_views_settings_plugin_html_erb___1809811401479238033_47447456910940'
  app/views/settings/plugin.html.erb:4:in `_app_views_settings_plugin_html_erb___1809811401479238033_47447456910940'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

команда which phantomjs возвращает следующее:
/usr/bin/phantomjs
Версия ОС: Ubuntu 16.04.3 LTS

**Comment by funk-yourself** [comment]
We recommend to upgrade to the [latest master version](https://github.com/centosadmin/redmine_telegram_common) of redmine_telegram_common.

**Comment by olemskoi** [comment]
Пожалуйста, откройте новую задачу, если после обновления проблема останется.
