### ISSUE TITLE
бот не отвечает на команды /start /connect

### ISSUE THREAD

**Issue by walkmanyd** [centosadmin/redmine_telegram_common#23]
Добрый вечер!
установил плагин, авторизовал клиента telegram на свой телефон, пытаюсь привязать аккаунт redmine к telegram, как это описано в readme но бот никак не реагирует на посылаемые ему команды.
лог:
D, [2017-10-26T23:32:58.899639 #3724] DEBUG -- : whoami: www-data

D, [2017-10-26T23:32:58.899827 #3724] DEBUG -- : Test
D, [2017-10-26T23:32:58.899918 #3724] DEBUG -- : {}
D, [2017-10-26T23:32:58.900687 #3724] DEBUG -- : /usr/bin/phantomjs --local-storage-path="/usr/share/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /usr/share/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://redmine.xxxx.xxx/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"
D, [2017-10-26T23:33:00.197381 #3724] DEBUG -- : https://redmine.xxxx.xxx/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
Push messaging is not supported.
success: api test
Error creating/accessing IndexedDB database [object Event]
   https://redmine.tubra.fit/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
'waitFor()' finished in 1007ms.

Подскажите пожалуйста что не так.

**Comment by constXife** [comment]
@walkmanyd добрый день, прошу прощения за долгую задержку ответа.

Надо понимать, что redmine_telegram_common это общая библиотека для наших нескольких плагинов. Поэтому сначала скажите в рамках которого плагина вы пытаетесь установить redmine_telegram_common? Покажите список ваших плагинов в редмайне, пожалуйста.

**Comment by olemskoi** [comment]
Пожалуйста, откройте задачу, если проблема все еще актуальна.
