### ISSUE TITLE
CODE#400 PHONE_CODE_EXPIRED

### ISSUE THREAD

**Issue by asteriskauto** [centosadmin/redmine_telegram_common#24]
нашел в faq: 
"I receiving error 'Error 400 PHONE_CODE_EXPIRED false 2' immediately after login
In this case wait 5-10 minutes and try login again"

Сутки пробовал - и на разные телефоны и тд, все равно выдают ошибку 400.

**Comment by neolite** [comment]
# Примерно такая же проблема
Версия redmine - 3.4
phantom 2.1.1

Только плагин ругался, что не может достучаться до сайта, пришлось в /etc/hosts прописать омен сайта на 127.0.0.1

Вкратце, доходит почти до конца, смс отправлят, но потом пишет в конце, что код устарел, но если зайти на саму папку с вебограмом, он норм сам авторизует и веб-версия телеграмма работает.

`D, [2018-02-05T10:11:52.132044 #23676] DEBUG -- : whoami: daemon

D, [2018-02-05T10:11:52.132151 #23676] DEBUG -- : Test
D, [2018-02-05T10:11:52.132185 #23676] DEBUG -- : {}
D, [2018-02-05T10:11:52.135344 #23676] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/opt/bitnami/apps/redmine/htdocs/tmp/telegram_common" --ignore-ssl-errors=yes /opt/bitnami/apps/redmine/htdocs/plugins/redmine_telegram_common/config/phantom-proxy.js "https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"
D, [2018-02-05T10:12:16.601436 #23676] DEBUG -- : whoami: daemon

D, [2018-02-05T10:12:16.601497 #23676] DEBUG -- : Login
D, [2018-02-05T10:12:16.601543 #23676] DEBUG -- : {:phone_number=>"79371234567"}
D, [2018-02-05T10:12:16.604138 #23676] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/opt/bitnami/apps/redmine/htdocs/tmp/telegram_common" --ignore-ssl-errors=yes /opt/bitnami/apps/redmine/htdocs/plugins/redmine_telegram_common/config/phantom-proxy.js "https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279371234567%22%7D&command=Login"
D, [2018-02-05T10:34:26.439465 #23683] DEBUG -- : whoami: daemon

D, [2018-02-05T10:34:26.439639 #23683] DEBUG -- : Test
D, [2018-02-05T10:34:26.439689 #23683] DEBUG -- : {}
D, [2018-02-05T10:34:26.442510 #23683] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/opt/bitnami/apps/redmine/htdocs/tmp/telegram_common" --ignore-ssl-errors=yes /opt/bitnami/apps/redmine/htdocs/plugins/redmine_telegram_common/config/phantom-proxy.js "https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"
D, [2018-02-05T10:34:27.990544 #23683] DEBUG -- : https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
Push messaging is not supported.
success: api test
Error creating/accessing IndexedDB database [object Event]
   https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
'waitFor()' finished in 1007ms.

D, [2018-02-05T10:35:05.825061 #23683] DEBUG -- : whoami: daemon

D, [2018-02-05T10:35:05.825140 #23683] DEBUG -- : Login
D, [2018-02-05T10:35:05.825174 #23683] DEBUG -- : {:phone_number=>"79371234567"}
D, [2018-02-05T10:35:05.826325 #23683] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/opt/bitnami/apps/redmine/htdocs/tmp/telegram_common" --ignore-ssl-errors=yes /opt/bitnami/apps/redmine/htdocs/plugins/redmine_telegram_common/config/phantom-proxy.js "https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279371234567%22%7D&command=Login"
D, [2018-02-05T10:35:10.400023 #23683] DEBUG -- : https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279371234567%22%7D&command=Login
Push messaging is not supported.
Error creating/accessing IndexedDB database [object Event]
   https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
[0.093] Send req_pq c4eb7e260aa29fa57d697e67cb66e533
[0.766] Got ResPQ ce2ea2e59fc543becf2bf97fefb13b59 2fb819b89d8e254d 14101943622620965665
[0.767] PQ factorization start [object Uint8Array]
[1.908] PQ factorization done 56905
[1.912] Send req_DH_params
[2.184] Done decrypting answer
[2.184] Verifying DH params
[2.184] dhPrime cmp OK
[2.184] 1 < gA < dhPrime-1 OK
[2.184] 2^{2048-64} < gA < dhPrime-2^{2048-64} OK
[2.184] Apply server time 1517826908 1517826908455 0 false
[2.390] Send set_client_DH_params
[3.057] Got Set_client_DH_params_answer dh_gen_ok
[3.059] Api call auth.sendCode
[3.460] Rpc response auth.sentCode
success: {"_":"auth.sentCode","pFlags":{"phone_registered":true},"flags":3,"type":{"_":"auth.sentCodeTypeApp","length":5},"phone_code_hash":"78f1bd8d885e0075f1","next_type":{"_":"auth.codeTypeSms"}}
'waitFor()' finished in 4021ms.

D, [2018-02-05T10:35:45.718549 #23683] DEBUG -- : whoami: daemon

D, [2018-02-05T10:35:45.718633 #23683] DEBUG -- : Login
D, [2018-02-05T10:35:45.718666 #23683] DEBUG -- : {:phone_number=>"79371234567", :phone_code_hash=>"78f1bd8d885e0075f1", :phone_code=>"94836"}
D, [2018-02-05T10:35:45.720004 #23683] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/opt/bitnami/apps/redmine/htdocs/tmp/telegram_common" --ignore-ssl-errors=yes /opt/bitnami/apps/redmine/htdocs/plugins/redmine_telegram_common/config/phantom-proxy.js "https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279371234567%22%2C%22phone_code_hash%22%3A%2278f1bd8d885e0075f1%22%2C%22phone_code%22%3A%2294836%22%7D&command=Login"
D, [2018-02-05T10:35:49.774948 #23683] DEBUG -- : https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2279371234567%22%2C%22phone_code_hash%22%3A%2278f1bd8d885e0075f1%22%2C%22phone_code%22%3A%2294836%22%7D&command=Login
Push messaging is not supported.
Error creating/accessing IndexedDB database [object Event]
   https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
[0.095] Send req_pq b176abb0811416c634637610496b26d2
[0.770] Got ResPQ a1f479e3420ac9ccc48575874c3d9ca3 11f6e4597bc2195b 14101943622620965665
[0.770] PQ factorization start [object Uint8Array]
[1.349] PQ factorization done 28998
[1.353] Send req_DH_params
[1.625] Done decrypting answer
[1.625] Verifying DH params
[1.625] dhPrime cmp OK
[1.625] 1 < gA < dhPrime-1 OK
[1.625] 2^{2048-64} < gA < dhPrime-2^{2048-64} OK
[1.626] Apply server time 1517826947 1517826947779 0 false
[1.838] Send set_client_DH_params
[2.520] Got Set_client_DH_params_answer dh_gen_ok
[2.521] Api call auth.signIn
[2.911] Rpc error [object Object]
[2.911] Error 400 PHONE_CODE_EXPIRED false 2
   https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/js/app.js : 24
failed: {"code":400,"type":"PHONE_CODE_EXPIRED","description":"CODE#400 PHONE_CODE_EXPIRED","originalError":{"_":"rpc_error","error_code":400,"error_message":"PHONE_CODE_EXPIRED"},"input":"auth.signIn","stack":"empty stack"}
'waitFor()' finished in 3510ms.

D, [2018-02-05T10:35:49.979772 #23683] DEBUG -- : whoami: daemon

D, [2018-02-05T10:35:49.979855 #23683] DEBUG -- : Test
D, [2018-02-05T10:35:49.979889 #23683] DEBUG -- : {}
D, [2018-02-05T10:35:49.981225 #23683] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/opt/bitnami/apps/redmine/htdocs/tmp/telegram_common" --ignore-ssl-errors=yes /opt/bitnami/apps/redmine/htdocs/plugins/redmine_telegram_common/config/phantom-proxy.js "https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"
D, [2018-02-05T10:35:51.542194 #23683] DEBUG -- : https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
Push messaging is not supported.
success: api test
Error creating/accessing IndexedDB database [object Event]
   https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
'waitFor()' finished in 1013ms.

D, [2018-02-05T10:38:00.224210 #23683] DEBUG -- : whoami: daemon

D, [2018-02-05T10:38:00.224334 #23683] DEBUG -- : Test
D, [2018-02-05T10:38:00.224371 #23683] DEBUG -- : {}
D, [2018-02-05T10:38:00.225691 #23683] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/opt/bitnami/apps/redmine/htdocs/tmp/telegram_common" --ignore-ssl-errors=yes /opt/bitnami/apps/redmine/htdocs/plugins/redmine_telegram_common/config/phantom-proxy.js "https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"
D, [2018-02-05T10:38:01.766850 #23683] DEBUG -- : https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
Push messaging is not supported.
success: api test
Error creating/accessing IndexedDB database [object Event]
   https://rm.domain.tld/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
'waitFor()' finished in 1006ms.

`

**Comment by asteriskauto** [comment]
у меня кстати решилось банальным "ничегонеделанием", отложил на сутки задачу, попробовал еще раз - все заработало:)

**Comment by olemskoi** [comment]
Попробуйте использовать последнюю версию наших плагинов из master. Мы перешли от использования webogram к tdlib - большинство проблем должны решиться.

Пожалуйста, откройте новую задачу при необходимости.
