### ISSUE TITLE
Error 400 API_ID_INVALID

### ISSUE THREAD

**Issue by raggajah** [centosadmin/redmine_telegram_common#30]
Добрый день,
никак не могу заставить работать плагин, при попытке получения кода авторизации вываливается в ошибку  CODE#400 API_ID_INVALID
Все сделал по инструкции, необходимые компоненты работают, в настройках плагина все 3 компонента в статусе "YES"
Помогите, пожалуйста, разобраться что за API ID такой..

telegram-cli.log:

D, [2018-01-11T15:52:43.148793 #26810] DEBUG -- : whoami: apache
D, [2018-01-11T15:52:43.148842 #26810] DEBUG -- : Login
D, [2018-01-11T15:52:43.148860 #26810] DEBUG -- : {:phone_number=>"7985XXXXXXX"}
D, [2018-01-11T15:52:43.149598 #26810] DEBUG -- : /usr/bin/phantomjs --local-storage-path="/var/www/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /var/www/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https:192.168.4.72/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%227985XXXXXXX%22%7D&command=Login"
D, [2018-01-11T15:52:46.492913 #26810] DEBUG -- : https:192.168.4.72/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%227985XXXXXX%22%7D&command=Login
Push messaging is not supported.
Error creating/accessing IndexedDB database [object Event]
   https://192.168.4.72/plugin_assets/redmine_telegram_common/webogram/js/app.js : 23
[0.049] Send req_pq fb07aee478dbe9071e69272c85a9e5bb
[0.390] Got ResPQ c13a541ffbe3b8fb98f8b28c9d6d1a87 17bce332dbc27c47 14101943622620965665
[0.390] PQ factorization start [object Uint8Array]
[1.070] PQ factorization done 25506
[1.075] Send req_DH_params
[1.236] Done decrypting answer
[1.236] Verifying DH params
[1.236] dhPrime cmp OK
[1.237] 1 < gA < dhPrime-1 OK
[1.237] 2^{2048-64} < gA < dhPrime-2^{2048-64} OK
[1.237] Apply server time 1515675164 1515675164607 0 false
[1.516] Send set_client_DH_params
[2.150] Got Set_client_DH_params_answer dh_gen_ok
[2.152] Api call auth.sendCode
[2.447] Rpc error [object Object]
[2.447] Error 400 API_ID_INVALID false 2
   https://192.168.4.72/plugin_assets/redmine_telegram_common/webogram/js/app.js : 24
failed: {"code":400,"type":"API_ID_INVALID","description":"CODE#400 API_ID_INVALID","originalError":{"_":"rpc_error","error_code":400,"error_message":"API_ID_INVALID"},"input":"auth.sendCode","stack":"empty stack"}
'waitFor()' finished in 3023ms.

PS пробовал как и master версию так и develop

**Comment by olemskoi** [comment]
Здравствуйте.

Проблема в недоступности из интернета URL https://192.168.4.72/plugin_assets/redmine_telegram_common/webogram/js/app.js

**Comment by VADZILko** [comment]
Доброго времени суток!
Столкнулся с аналогичной проблемой
URL до app.js доступен из интернета, только есть подозрения что открывается не совсем то, что должно
```
D, [2018-01-12T01:21:48.070853 #17337] DEBUG -- : whoami: redmine

D, [2018-01-12T01:21:48.070888 #17337] DEBUG -- : Login
D, [2018-01-12T01:21:48.070903 #17337] DEBUG -- : {:phone_number=>"7707XXXXX44"}
D, [2018-01-12T01:21:48.071694 #17337] DEBUG -- : /usr/bin/phantomjs --local-storage-path="/var/www/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /var/www/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://support.acconline.kz/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%227707XXXXX44%22%7D&command=Login"
D, [2018-01-12T01:21:50.368353 #17337] DEBUG -- : https://support.acconline.kz/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%227707XXXXX44%22%7D&command=Login
Push messaging is not supported.
[0.049] Send req_pq 6bXXXXXXXXXXXXXXXXXXXXXXXXXXXc50
[0.192] Got ResPQ 850XXXXXXXXXXXXXXXXXXXXXXXXXX2f8 120XXXXXXXXXX757d 14XXXXXXXXXXXXXXX665
[0.192] PQ factorization start [object Uint8Array]
[0.278] PQ factorization done 3352
[0.284] Send req_DH_params
[0.362] Done decrypting answer
[0.362] Verifying DH params
[0.362] dhPrime cmp OK
[0.362] 1 < gA < dhPrime-1 OK
[0.362] 2^{2048-64} < gA < dhPrime-2^{2048-64} OK
[0.363] Apply server time 1515698508 1515698508637 0 false
[0.611] Send set_client_DH_params
[1.130] Got Set_client_DH_params_answer dh_gen_ok
[1.131] Api call auth.sendCode
[1.322] Rpc error [object Object]
[1.322] Error 400 API_ID_INVALID false 2
   https://support.acconline.kz/plugin_assets/redmine_telegram_common/webogram/js/app.js : 24
failed: {"code":400,"type":"API_ID_INVALID","description":"CODE#400 API_ID_INVALID","originalError":{"_":"rpc_error","error_code":400,"error_message":"API_ID_INVALID"},"input":"auth.sendCode","stack":"empty stack"}
'waitFor()' finished in 2000ms.
```

**Comment by olemskoi** [comment]
Попробуйте сертификат от Let's Encrypt. Возможно проблема в валидности сертификата?

**Comment by VADZILko** [comment]
В дополнение:
На сервере установлены две сетевые карты, eth0 - смотрит во внутреннюю сеть, а eth1 - в интернет. 
Defroute ведет в интернет через eth1. На eth1 открыты порты только 80 и 443.

> Попробуйте сертификат от Let's Encrypt. Возможно проблема в валидности сертификата?

Сейчас попробую сертификат от Let's Encrypt

**Comment by constXife** [comment]
Вообще больше похоже на то, что валится из-за ошибки [1.322] Error 400 API_ID_INVALID false 2

У вас немодифицированные файлы плагина?

**Comment by constXife** [comment]
Эта ошибка означает, что в вебограме указан неверный API_ID. Но это странно, так как там указан наш API_ID и он у нас работает.

Попробуйте склонировать плагин с ветки develop и убедиться, что файлы идентичные, немодифицированные.

**Comment by VADZILko** [comment]
Устанавливал по инструкции, файлы не модифицировал. Сейчас попробую перейти на ветку develop.

> Сейчас попробую сертификат от Let's Encrypt
Результата, не дало

**Comment by VADZILko** [comment]
> Эта ошибка означает, что в вебограме указан неверный API_ID. Но это странно, так как там указан наш API_ID и он у нас работает.
> 
> Попробуйте склонировать плагин с ветки develop и убедиться, что файлы идентичные, немодифицированные.

Проверил, все файлы не модифицированные.
На версии плагина 0.1.4-dev при попытке авторизации выходит такая же ошибка

**Comment by noteMASTER11** [comment]
То же самое. Перезаливали weborram и /assets/webogram из офю репозиториев - вдруг ошибка в них. Но нет, осталась.

Куда вообще API ключи прописываются?

**Comment by constXife** [comment]
Они уже прописаны в коде API ключи разработчика, поэтому и странно.

https://github.com/centosadmin/redmine_telegram_common/blob/1805f884a3b54ece808bd3f90e30ee1371de7390/app/webogram/app/js/lib/mtproto.js#L61

Я ещё завтра посмотрю.

**Comment by yakhlakov** [comment]
Добрый день.
Аналогичная ошибка, все вышеописанные способы не помогли.

**Comment by constXife** [comment]
Есть возможность пустить меня на сервер, где проявляется эта проблема? Или быть может есть возможность поднять тестовый сервер с такой проблемой?

Ну или хотя бы скиньте, пожалуйста, информацию о версиях редмайна, плагинах, операционной системы, версии phantomjs.

**Comment by VADZILko** [comment]
> Есть возможность пустить меня на сервер, где проявляется эта проблема? Или быть может есть возможность поднять тестовый сервер с такой проблемой?

Могу пустить к себе на сервер. Данные на почту отправлю

**Comment by yakhlakov** [comment]
> Ну или хотя бы скиньте, пожалуйста, информацию о версиях редмайна, плагинах, операционной системы, версии phantomjs.

Ubuntu 16.04
Ruby 2.4
Rails 4.2.8
Redine 3.4.4
phantomjs 2.1.1
plugins:
A common libraries 2.4.2
Bestest Punch Clock for Redmine 1.2.0	
Clipboard image paste 1.12	
Custom Menu Redmine 1.8.1
Extra Queries plugin 2.3.0
Global Roles plugin 2.2.1	
Redmine Periodictask plugin 3.2.0	
Redmine Checklists plugin (Light version) 3.1.10
Redmine Edit Custom Fields plugin 0.0.5	
Redmine Intouch plugin 1.0.1
Redmine Issue Tabs plugin 1.3.0	
Redmine Issue Templates plugin 0.1.8
Redmine Logs plugin 0.1.1
Redmine People plugin (Light version) 1.3.2	
Redmine Sender 1.4.1
Redmine Sidekiq plugin 2.1.0
Redmine Telegram Common plugin 0.1.3
Redmine Work Time plugin 0.3.4
Redmine User Mentions plugin 1.0.1
Under Construction 2.0.5
Unread Issues plugin 2.2.0
Usability plugin 2.3.1

**Comment by yakhlakov** [comment]
При попытке перейти по урлу из логов:
```
D, [2018-01-25T13:42:38.526715 #30667] DEBUG -- : Login
D, [2018-01-25T13:42:38.526762 #30667] DEBUG -- : {:phone_number=>"7XXXXXXXXXX"}
D, [2018-01-25T13:42:38.527873 #30667] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/var/data/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /var/data/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://e.com/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%227XXXXXXXXXX%22%7D&command=Login"
D, [2018-01-25T13:42:39.734207 #30667] DEBUG -- : https://e.com/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%227XXXXXXXXXX%22%7D&command=Login
Push messaging is not supported.
[0.050] Api call auth.sendCode
[0.504] Rpc error [object Object]
[0.504] Error 400 API_ID_INVALID false 2
   https://e.com/plugin_assets/redmine_telegram_common/webogram/js/app.js : 24
failed: {"code":400,"type":"API_ID_INVALID","description":"CODE#400 API_ID_INVALID","originalError":{"_":"rpc_error","error_code":400,"error_message":"API_ID_INVALID"},"input":"auth.sendCode","stack":"empty stack"}
'waitFor()' finished in 1002ms.
```
![image](https://user-images.githubusercontent.com/34373452/35387846-7403a7ea-01e2-11e8-9b12-a65bd7851915.png)

Иногда лог такой:
```
D, [2018-01-25T11:39:02.270023 #28339] DEBUG -- : Login
D, [2018-01-25T11:39:02.270041 #28339] DEBUG -- : {:phone_number=>"7XXXXXXXXXX"}
D, [2018-01-25T11:39:02.270871 #28339] DEBUG -- : /usr/local/bin/phantomjs --local-storage-path="/var/data/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /var/data/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://e.com/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%227XXXXXXXXXX%22%7D&command=Login"
D, [2018-01-25T11:39:05.499623 #28339] DEBUG -- : https://e.com/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%227XXXXXXXXXX%22%7D&command=Login
Push messaging is not supported.
[0.052] Send req_pq 2f445c3156503978e713deeacfd3e76d
[0.339] Got ResPQ b789ebce70357d92f1da4a62a0de6ef0 1b677eebdedbb0f1 14101943622620965665
[0.339] PQ factorization start [object Uint8Array]
[1.285] PQ factorization done 47340
[1.290] Send req_DH_params
[1.431] Done decrypting answer
[1.431] Verifying DH params
[1.431] dhPrime cmp OK
[1.431] 1 < gA < dhPrime-1 OK
[1.432] 2^{2048-64} < gA < dhPrime-2^{2048-64} OK
[1.432] Apply server time 1516869545 1516869543842 2 false
[1.638] Send set_client_DH_params
[2.174] Got Set_client_DH_params_answer dh_gen_ok
[2.176] Api call auth.sendCode
[2.445] Rpc error [object Object]
[2.445] Error 400 API_ID_INVALID false 2
   https://e.com/plugin_assets/redmine_telegram_common/webogram/js/app.js : 24
failed: {"code":400,"type":"API_ID_INVALID","description":"CODE#400 API_ID_INVALID","originalError":{"_":"rpc_error","error_code":400,"error_message":"API_ID_INVALID"},"input":"auth.sendCode","stack":"empty stack"}
'waitFor()' finished in 3021ms.
```
Файла /partials/desktop/api.html нет (и, кажется, не должно быть) в соответствующей директории.

**Comment by VADZILko** [comment]
Ну что? Есть каки-нить идеи?

**Comment by VADZILko** [comment]
Попробовал выполнить команду авторизации "руками":
```
[redmine@srv-spt telegram_common]$ /usr/bin/phantomjs --local-storage-path="/var/www/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /var/www/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://support.acconline.kz/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2277071236844%22%7D&command=Login"
https://support.acconline.kz/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2277071236844%22%7D&command=Login
Push messaging is not supported.
[0.047] Api call auth.sendCode
[0.201] Bad server salt [object Object]
[0.268] Bad server salt [object Object]
[0.342] Rpc error [object Object]
[0.342] Error 400 API_ID_INVALID false 2
   https://support.acconline.kz/plugin_assets/redmine_telegram_common/webogram/js/app.js : 24
failed: {"code":400,"type":"API_ID_INVALID","description":"CODE#400 API_ID_INVALID","originalError":{"_":"rpc_error","error_code":400,"error_message":"API_ID_INVALID"},"input":"auth.sendCode","stack":"empty stack"}
'waitFor()' finished in 1001ms.
```
Может это что-то даст

**Comment by makarich** [comment]
Такая же ошибка. Пробовал устанавливать свежий https://github.com/zhukov/webogram, с ним тоже 
"CODE#400 API_ID_INVALID"

**Comment by yakhlakov** [comment]
Если скачать webogram и аккуратно перетянуть его в директорию redmine/public/plugin_assets/redmine_telegram_common/webogram, то по адресу https://domain.com/plugin_assets/redmine_telegram_common/webogram/index.html авторизация проходит. Но это тоже не помогает ;(

**Comment by makarich** [comment]
Именно так и делал
[
![screenshot-redmine srcc su-2018-01-31-10-50-50-656](https://user-images.githubusercontent.com/1941162/35611021-b4d905a8-0674-11e8-92aa-6eff9cc8d854.png)
](url)

**Comment by constXife** [comment]
Добрый день, я не забыл про вашу задачу, просто у меня были насыщенные дни и пока не смог добраться до задачи, но очень надеюсь, что в ближайшие пару дней я смогу всё же потыкать.

**Comment by funk-yourself** [comment]
Временное решение (прошу отписаться, помогло ли):
1. Регистрируем собственное приложение на https://my.telegram.org/apps
2. В app/webogram/app/js/lib/config.js на 21-22 строчках прописываем свои данные.

**Comment by yakhlakov** [comment]
Добрый день. Не помогло (

**Comment by VADZILko** [comment]
> Временное решение (прошу отписаться, помогло ли):
> 
>     Регистрируем собственное приложение на https://my.telegram.org/apps
>     В app/webogram/app/js/lib/config.js на 21-22 строчках прописываем свои данные.
> 

Создал собственное приложение и прописал в указанном файле, результат тотже

```
D, [2018-02-01T14:17:25.368419 #4909] DEBUG -- : whoami: redmine

D, [2018-02-01T14:17:25.368506 #4909] DEBUG -- : Test
D, [2018-02-01T14:17:25.368539 #4909] DEBUG -- : {}
D, [2018-02-01T14:17:25.369412 #4909] DEBUG -- : /usr/bin/phantomjs --local-storage-path="/var/www/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /var/www/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://support.acconline.kz/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test"
D, [2018-02-01T14:17:26.666940 #4909] DEBUG -- : https://support.acconline.kz/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%7D&command=Test
Push messaging is not supported.
success: api test
'waitFor()' finished in 1000ms.

D, [2018-02-01T14:19:21.650930 #4909] DEBUG -- : whoami: redmine

D, [2018-02-01T14:19:21.650975 #4909] DEBUG -- : Login
D, [2018-02-01T14:19:21.650993 #4909] DEBUG -- : {:phone_number=>"77071236844"}
D, [2018-02-01T14:19:21.652040 #4909] DEBUG -- : /usr/bin/phantomjs --local-storage-path="/var/www/redmine/tmp/telegram_common" --ignore-ssl-errors=yes /var/www/redmine/plugins/redmine_telegram_common/config/phantom-proxy.js "https://support.acconline.kz/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2277071236844%22%7D&command=Login"
D, [2018-02-01T14:19:24.976182 #4909] DEBUG -- : https://support.acconline.kz/plugin_assets/redmine_telegram_common/webogram/index.html#/api?args=%7B%22phone_number%22%3A%2277071236844%22%7D&command=Login
Push messaging is not supported.
[0.056] Send req_pq 11d12ceea6446c85ed93e3801bb568cb
[0.201] Got ResPQ 51184984ca3b7fe060f8e31b394c2f34 258a49a3c2af7c09 14101943622620965665
[0.201] PQ factorization start [object Uint8Array]
[0.969] PQ factorization done 31684
[0.974] Send req_DH_params
[1.053] Done decrypting answer
[1.053] Verifying DH params
[1.053] dhPrime cmp OK
[1.053] 1 < gA < dhPrime-1 OK
[1.054] 2^{2048-64} < gA < dhPrime-2^{2048-64} OK
[1.054] Apply server time 1517473162 1517473162939 0 false
[1.304] Send set_client_DH_params
[2.040] Got Set_client_DH_params_answer dh_gen_ok
[2.042] Api call auth.sendCode
[2.234] Rpc error [object Object]
[2.235] Error 400 API_ID_INVALID false 2
   https://support.acconline.kz/plugin_assets/redmine_telegram_common/webogram/js/app.js : 24
failed: {"code":400,"type":"API_ID_INVALID","description":"CODE#400 API_ID_INVALID","originalError":{"_":"rpc_error","error_code":400,"error_message":"API_ID_INVALID"},"input":"auth.sendCode","stack":"empty stack"}
'waitFor()' finished in 3000ms.
```

**Comment by yakhlakov** [comment]
> Может дело в используемом вебсервере на котором крутиться редмайн?
> yakhlakov Вы какой используете? У нас nginx+passenger
Аналогично. 
Кое-кто подсказал, что возможно, поможет повторная сборка исходников с новым app id :)

**Comment by constXife** [comment]
Да, вышеупомянутое решение должно помочь, но в плагине используется скомпилированная версия вебограма.

Вот тут краткая инструкция.

1.  Регистрируем собственное приложение на https://my.telegram.org/apps
2. В app/webogram/app/js/lib/config.js на 21-22 строчках прописываем свои данные.
3. Устанавливаем на каком-нибудь компьютере nodejs
4. Устанавливаем gulp (npm install -g gulp)
5. Идем в app/webogram
6. Запускаем npm install
7. Запускаем gulp watch и убеждаемся что по адресу http://localhost:8000/app/index.html что-то открывается (должен появиться интерфейс логина в вебограм)
8. Далее удаляем папку assets/webogram
9. Запускаем из app/webogram команду gulp publish
10. Затем папку assets/webogram копируем на ваш сервер с редмайном, заменяем соответствующую папку плагина

https://github.com/centosadmin/redmine_telegram_common#plugin-development


Если у кого не получится, то напишите мне на почту с api_app_id и api_app_hash я вам скомпилю как будет время файлы.

**Comment by constXife** [comment]
Мы сейчас активно работаем над новой версией плагина, где улучшим работу с телеграмом, чтобы не было столько проблем.

**Comment by hatsnal** [comment]
А должен ли сертификат ссл совпадать с FQDN ? может в этом проблема ?

**Comment by hatsnal** [comment]
@constXife сможеет к нам на сервер зайти посмотреть ?

**Comment by VADZILko** [comment]
Получилось сделать по инструкции, авторизация плагина прошла успешно.
Заметил, что если нажать после этого на кнопку "Применить", то исчезает текст с указанием номера, к которому привязан плагин

**Comment by hatsnal** [comment]
@VADZILko получилось сделать по какой инструкции? пересобрав приложение ?

**Comment by yakhlakov** [comment]
+1
У меня тоже получилось.
@hatsnal , по этой [инструкции ](https://github.com/centosadmin/redmine_telegram_common/issues/30#issuecomment-362246244)

**Comment by VADZILko** [comment]
@hatsnal по этой [инструкции ](https://github.com/centosadmin/redmine_telegram_common/issues/30#issuecomment-362246244)

**Comment by hatsnal** [comment]
@VADZILko а можешь поделиться готовой папкой webogram ?)

**Comment by hatsnal** [comment]
@constXife а как скоро ждать новую версию ?

**Comment by hatsnal** [comment]
@VADZILko подскажи как свое приложение создать? Пытаюсь создать и выдает Incorrect app title&#33;

**Comment by olemskoi** [comment]
Укажите BlaBlaApp ;-)

**Comment by hatsnal** [comment]
@olemskoi да с этим разобрался, но не могу скомпилировать, можешь помочь ?

**Comment by olemskoi** [comment]
> @olemskoi да с этим разобрался, но не могу скомпилировать, можешь помочь ?
Выше - инструкция. Подробнее не подскажу.

**Comment by neolite** [comment]
Была такая же проблема, после компиляции с другими APP_ID решилась, но возникла новая проблема #24

**Comment by funk-yourself** [comment]
В ветке master обновленная версия плагина, в которой вместо webogram используется [tdlib-ruby](https://github.com/centosadmin/tdlib-ruby). Не забудьте посмотреть обновленные требования в README. Если будут проблемы со сборкой tdlib, могу отправить скомпилированные версии под Ubuntu 16.04 и Mac OS High Sierra.

**Comment by makarich** [comment]
Бот авторизовался, но что то на команды все равно не отвечает или так и должно быть?
Где теперь логи смотреть?

**Comment by funk-yourself** [comment]
@makarich бот есть в контактах у юзера, привязанного к redmine_telegram_common? И да, redmine_chat_telegram также нужно обновить.

**Comment by makarich** [comment]
redmine_chat_telegram не использую, только этот https://github.com/centosadmin/redmine_intouch

**Comment by neolite** [comment]
Я скомпилил tdlib по инструкции, но какой файл из директории build копировать в redmine/vendor?

**Comment by funk-yourself** [comment]
@neolite дебиан нет под рукой, но вот под убунту 16.04 (вроде базируется на stretch, м.б. подойдет): https://drive.google.com/file/d/1FIrNnt3iua4e6Tu6-o7oSc0SXNt-_Vj4/view?usp=sharing

**Comment by neolite** [comment]
Спасибо, заработало! Причем я в докере скомпилил для дебиана libtdjson, но он вызывал segfault, может быть потому что я его clangом компилил?

**Comment by olemskoi** [comment]
Закрываю эту задачу. У кого остались проблемы в плагинах из master, пожалуйста, откройте новую задачу.
