### ISSUE TITLE
500 internal server error

### ISSUE THREAD

**Issue by tesey27** [centosadmin/redmine_telegram_common#48]
Здравствуйте. У меня выходит ошибка 500 когда пытаюсь авторизовать клиент телеграм. 
в логах такие записи
Completed 500 Internal Server Error in 9ms (ActiveRecord: 3.1ms)

Fiddle::DLError (cannot find the function: td_json_client_create()):
  plugins/redmine_telegram_common/lib/telegram_common/tdlib/dependency_providers.rb:6:in `client'
  plugins/redmine_telegram_common/lib/telegram_common/tdlib/dependency_providers.rb:21:in `authenticate'
  plugins/redmine_telegram_common/app/controllers/redmine_telegram_setup_controller.rb:11:in `step_2'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'

**Comment by tesey27** [comment]
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

**Comment by tesey27** [comment]
В логах самого плагина ничего нет.

**Comment by funk-yourself** [comment]
Добрый день! libtdjson лежит в папке vendor?

**Comment by tesey27** [comment]
добрый день. Спасибо за ответ. Я только начал осваивать ubuntu, к сожалению не знаком с этой библиотекой. Как ее установит?

**Comment by funk-yourself** [comment]
Либо собрать самостоятельно (https://core.telegram.org/tdlib/docs/#building), либо воспользоваться скомпилированной мной версией: https://drive.google.com/file/d/1FIrNnt3iua4e6Tu6-o7oSc0SXNt-_Vj4/view?usp=sharing (компилировал под Ubuntu 16.04, нужно положить в папку папка_redmine/vendor)

**Comment by tesey27** [comment]
Спасибо) все работает. Telegram Database library? Это та библиотека. Ее я вроде скомпилировал в папке vendor.
