### ISSUE TITLE
Bot domain invalid

### ISSUE THREAD

**Issue by Dal1ght** [centosadmin/redmine_telegram_common#61]
Добрый день.

Установил и настроил плагин. Бот подключился. После ввода команды /connect высылает ссылку для подключения, но на странице отображается ошибка "_Bot domain invalid_". Версия плагина 0.5.0

**Comment by olemskoi** [comment]
Здравствуйте. Установите домен у telegram bot-а через botfather.

**Comment by Dal1ght** [comment]
Спасибо, помогло.
