### ISSUE TITLE
Telegram Bot Token not found

### ISSUE THREAD

**Issue by dronmaxman** [centosadmin/redmine_telegram_common#79]
ruby 2.3.3p222
Redmine version:  3.3.1
Database: mariadb
Placed the tblib build under vendor directory.
Bundle install worked fine.

**To make telegram client working you should follow steps:**
Be sure you set correct host in Redmine settings
**Go to the plugin settings page**
Press "Authorize Telegram client" button and follow instructions

**После установки плагина страница redmine больше не открывается, соответственно, как настроить бота (ввести API ключ)?**
We're sorry, but something went wrong.
We've been notified about this issue and we'll take a look at it shortly.

**В логе бота (telegram_common/bot.log) видим ошибку.**
ERROR -- : Telegram Bot Token not found. Please set it in the plugin config web-interface.

**В логе Tlib ( telegram_common/tdlib.log)**
[ 1][t 0][1529331012.030710936][ClientJson.cpp:76][&status.is_error()]  Failed to parse [request:{\0042@type\0042:\0042setTdlibParameters\0042,\0042parameters\0042:{\0042@type\0042:\0042tdlibParameters\
0042,\0042api_id\0042:\0042\0042,\0042api_hash\0042:\0042\0042,\0042use_test_dc\0042:false,\0042database_directory\0042:\0042/usr/share/redmine/tmp/redmine_telegram_common/tdlib/db\0042,\0042files_direc
tory\0042:\0042/usr/share/redmine/tmp/redmine_telegram_common/tdlib/files\0042,\0042use_chat_info_database\0042:true,\0042use_secret_chats\0042:true,\0042use_message_database\0042:true,\0042system_langu
age_code\0042:\0042en\0042,\0042device_model\0042:\0042Ruby TD client\0042,\0042system_version\0042:\0042Unknown\0042,\0042application_version\0042:\00421.0\0042,\0042enable_storage_optimizer\0042:true,
\0042ignore_file_names\0042:false}}] [Error : 0 : Can't parse "" as number]

**Comment by funk-yourself** [comment]
Нужен стектрейс ошибки, которая происходит при попытке открыть Redmine.

**Comment by dronmaxman** [comment]
**Все что есть в production.log**

Starting Pretend plugin for RedMine
Starting Summable Fields plugin for Redmine
DEPRECATION WARNING: Defining a route where `to` is a controller without an action is deprecated. Please change `to: 'banner'` to `controller: 'banner'`. (called from block (3 levels) in <top (required)> at (eval):2)
Migrating to AddLastTryAtToTelegramCommonAccounts (4)
Migrating to ChangeBlockedToTelegramCommonAccounts (3)
Migrating to AddBlockedToTelegramCommonAccounts (2)
Migrating to CreateTelegramCommonAccounts (1)

**Comment by dronmaxman** [comment]
В логе библитеки TBlib больше информации.

[tblib.log](https://github.com/centosadmin/redmine_telegram_common/files/2114071/tblib.log)

**Comment by funk-yourself** [comment]
Клиент tdlib не запускается при запуске сервера и не может препятствовать запуску Redmine. В логе tdlib ошибка, произошедшая во время выполнения rake-команды (из-за неправильной конфигурации). Повторюсь, что нужен стектрейс исключения при попытке открытия страницы в Redmine.

**Comment by dronmaxman** [comment]
> Повторюсь, что нужен стектрейс исключения при попытке открытия страницы в Redmine.

Как это сделать?

**Comment by dronmaxman** [comment]
Нашел свои грабли, надо было внимательнее смотреть лог апача.
sudo chown www-data:www-data /usr/share/redmine/log/telegram_common/tdlib.log


Но запустить бота в режиме  getUpdates не получается.
Настройки плагина.
![image](https://user-images.githubusercontent.com/15871669/41876691-4e0424c2-78d7-11e8-9af2-888dc19047bd.png)

При выполнении команды ничего интересного не происходит.
sudo bundle exec rake telegram_common:bot --trace
** Invoke telegram_common:bot (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute telegram_common:bot
admin@web-rm02:/usr/share/redmine$

Есть только ругательства в telegram_common/tdlib.log ( Sending error for request 4: error { code = 401 message = "Unauthorized" })
[tdlib.log](https://github.com/centosadmin/redmine_telegram_common/files/2134823/tdlib.log)

Подскажите куда копать?

**Comment by dronmaxman** [comment]
"Спасибо все кто помог". Проблема была в двухфакторной аутентификации для моего телегам аккаунта.
