### ISSUE TITLE
Error : 0 : Can't parse  as number

### ISSUE THREAD

**Issue by dronmaxman** [centosadmin/redmine_telegram_common#82]
ruby 2.3.3p222
Redmine version: 3.3.1
Database: mariadb

Не могу авторизовать клиента Телеграмм.

 Failed to parse [request:{\0042@type\0042:\0042setTdlibParameters\0042,\0042parameters\0042:{\0042@type\0042:\0042tdlibParameters\
0042,\0042api_id\0042:\00426281a118059d02b0841600e979e7bf08\0042,\0042api_hash\0042:\0042570539390:AAHEUaPxSCT6D8n-35efQV9hXnVhujo7-iA\0042,\0042use_test_dc\0042:false,\0042database_directory\0042:\0042
/usr/share/redmine/tmp/redmine_telegram_common/tdlib/db\0042,\0042files_directory\0042:\0042/usr/share/redmine/tmp/redmine_telegram_common/tdlib/files\0042,\0042use_chat_info_database\0042:true,\0042use
_secret_chats\0042:true,\0042use_message_database\0042:true,\0042system_language_code\0042:\0042en\0042,\0042device_model\0042:\0042Ruby TD client\0042,\0042system_version\0042:\0042Unknown\0042,\0042ap
plication_version\0042:\00421.0\0042,\0042enable_storage_optimizer\0042:true,\0042ignore_file_names\0042:false}}] [Error : 0 : Can't parse "6281a118059d02b0841600e979e7bf08" as number]

**Comment by dronmaxman** [comment]
теоритически должны быть какие-то запросы в сторону api.telegram.org. Смотрю tcpdump-ом, но ничего не вижу. Есть только лог apache2.

[ 2018-07-09 22:47:30.2156 1638/7f57528b4700 age/Cor/Con/InternalUtils.cpp:112 ]: [Client 2-4] Sending 502 response: application did not send a complete response
[ 2018-07-09 22:47:35.0234 1638/7f57598b3700 age/Cor/App/Poo/AnalyticsCollection.cpp:102 ]: Process (pid=1789, group=redmine_default) no longer exists! Detaching it from the pool.
[ 2018-07-09 22:47:35.0235 1638/7f57598b3700 age/Cor/CoreMain.cpp:819 ]: Checking whether to disconnect long-running connections for process 1789, application redmine_default

**Comment by funk-yourself** [comment]
tdlib не может обработать api_id. Это должно быть целое число, а у вас там строка, а в api_hash, похоже, токен от бота, а не hash приложения. Кстати, лучше уберите эти данные из сообщения: они должны быть приватными.

**Comment by dronmaxman** [comment]
Пошел за кувалдой ровнять руки... Перепутал местами api_id с api_hash.

Спасибо)

**Comment by dronmaxman** [comment]
Пошел за кувалдой ровнять руки... Перепутал местами api_id с api_hash.

Спасибо)

**Comment by dronmaxman** [comment]
Пошел за кувалдой ровнять руки... Перепутал местами api_id с api_hash.

Спасибо)
